// Auto-generated by CLIO. Do not edit by hand.
import Foundation

struct SentimentResult: Codable, Sendable {
    var label: String
    var confidence: Double

    static let jsonSchema = """
    {
      "type": "object",
      "properties": {
        "label": {
          "enum": [
            "positive",
            "negative",
            "neutral"
          ]
        },
        "confidence": {
          "type": "number"
        }
      },
      "required": [
        "label",
        "confidence"
      ],
      "additionalProperties": false,
      "x-clio-assert": {
        "kind": "compare",
        "op": ">=",
        "left": {
          "kind": "ident",
          "name": "confidence"
        },
        "right": {
          "kind": "float",
          "value": 0.0
        }
      }
    }
    """

    func validate() throws {
        try Validate.check(self, against: Self.jsonSchema)
    }
}
