package steps

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/anthropics/anthropic-sdk-go"
	"customer_retention/clio_runtime/cache"
	"customer_retention/contracts"
)

type DetectChurnIn struct {
	Customers []struct { Name string `json:"name"`; Revenue float64 `json:"revenue"` } `json:"customers"`
}

type DetectChurnOut struct {
	Risks []contracts.CustomerRisk `json:"risks"`
}

// DetectChurn implements the 'detect_churn' judgment step (Anthropic SDK).
func DetectChurn(ctx context.Context, in DetectChurnIn) (DetectChurnOut, error) {
	// 1. Build prompt from input.
	inJSON, err := json.Marshal(in)
	if err != nil {
		return DetectChurnOut{}, fmt.Errorf("detect_churn: marshal input: %w", err)
	}
	prompt := fmt.Sprintf("Process this input and return JSON matching the output schema.\n\nInput:\n%s", string(inJSON))

	ttl := int64(86400)
	ttlPtr := &ttl
	cacheDir := cache.CacheDirFromEnv()
	key := cache.Key("detect_churn", "claude-haiku-4-5-20251001", prompt, "")
	if v, ok := cache.Lookup(cacheDir, "detect_churn", key, ttlPtr); ok {
		var cached DetectChurnOut
		if err := json.Unmarshal([]byte(v), &cached); err == nil {
			return cached, nil
		}
	}

	var out DetectChurnOut
	for attempt := 0; attempt < 3; attempt++ {
		if attempt > 0 {
			time.Sleep(time.Duration(1<<uint(attempt-1)) * time.Second)
		}
		client := anthropic.NewClient()
		resp, respErr := client.Messages.New(ctx, anthropic.MessageNewParams{
			Model:     "claude-haiku-4-5-20251001",
			MaxTokens: int64(8192),
			System: []anthropic.TextBlockParam{{Text: "You are a precise function. Return only valid JSON matching the requested output schema. No prose."}},
			Messages: []anthropic.MessageParam{anthropic.NewUserMessage(anthropic.NewTextBlock(prompt))},
		})
		if respErr != nil {
			continue
		}
		if len(resp.Content) == 0 {
			continue
		}
		raw := resp.Content[0].Text
		if parseErr := json.Unmarshal([]byte(raw), &out); parseErr != nil {
			continue
		}
		if validatable, ok := any(&out).(interface{ Validate(context.Context) error }); ok {
			if validateErr := validatable.Validate(ctx); validateErr != nil {
				continue
			}
		}
	if rawBytes, err := json.Marshal(out); err == nil {
	_ = cache.Store(cacheDir, "detect_churn", key, "claude-haiku-4-5-20251001", string(rawBytes))
	}
		return out, nil
	}

	// ON_FAIL fallback: detect_churn_naive
	fbOut, fbErr := DetectChurnNaive(ctx, DetectChurnNaiveIn{Customers: in.Customers})
	if fbErr != nil {
		return DetectChurnOut{}, fmt.Errorf("churn detection exhausted: %w", fbErr)
	}
	out.Risks = fbOut.Risks
	return out, nil
}
