"""Step: foo (mode=exact)

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import json
import sys


def main() -> int:
    # TODO: implement step body once TAKES/GIVES are added.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
