from enum import Enum


class Keyword(str, Enum):
    """Closed enum of every keyword recognized by the lexer."""
    STEP = "STEP"
    MODE = "MODE"
    EXACT = "exact"
    JUDGMENT = "judgment"
    TAKES = "TAKES"
    GIVES = "GIVES"
    INT = "int"
    FLOAT = "float"
    STR = "str"
    BOOL = "bool"
    LIST = "List"
    ENUM = "enum"
    CONTRACT = "CONTRACT"
    SHAPE = "SHAPE"
    CSV = "CSV"
    FLOW = "FLOW"
    ASSERT = "ASSERT"
    RESOURCES = "RESOURCES"
    TARGET = "target"
    MODELS = "models"
    CLAUDE_CLI = "claude-cli"
    HAIKU = "haiku"
    SONNET = "sonnet"
    OPUS = "opus"
    BUDGET = "budget"
    PREFER = "prefer"
    STRATEGY = "strategy"
