// Auto-generated by CLIO. Do not edit by hand.
import Foundation

struct RiskAssessment: Codable, Sendable {
    var level: String
    var score: Double

    static let jsonSchema = """
    {
      "type": "object",
      "properties": {
        "level": {
          "enum": [
            "low",
            "mid",
            "high"
          ]
        },
        "score": {
          "type": "number"
        }
      },
      "required": [
        "level",
        "score"
      ],
      "additionalProperties": false
    }
    """

    func validate() throws {
        try Validate.check(self, against: Self.jsonSchema)
    }
}
