package flow

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"

	"pipeline/steps"
)

func Run(ctx context.Context, kwargs map[string]any) (map[string]any, error) {
	state := map[string]any{}

	loadOut, err := steps.Load(ctx, steps.LoadIn{ File: "customers.csv" })
	if err != nil {
		return nil, err
	}
	state["rows"] = loadOut

	summariseOut, err := steps.Summarise(ctx, steps.SummariseIn{ Rows: state["rows"].(steps.LoadOut).Rows })
	if err != nil {
		return nil, err
	}
	state["total"] = summariseOut

	return state, nil
}
