package flow

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"

	"pipeline/steps"
)

func Run(ctx context.Context, kwargs map[string]any) (map[string]any, error) {
	state := map[string]any{}

	loadOut, err := steps.Load(ctx, steps.LoadIn{ File: kwargs["file"].(string) })
	if err != nil {
		return nil, err
	}
	state["load"] = loadOut

	summariseOut, err := steps.Summarise(ctx, steps.SummariseIn{ Rows: loadOut.Rows })
	if err != nil {
		return nil, err
	}
	state["summarise"] = summariseOut

	return state, nil
}
