"""Auto-generated by clio v0.15 from TEST refine_loop_terminates_with_known_article.

Do not edit by hand: re-run `clio compile` to regenerate.
"""

from iterative_refiner.flow import run


def test_refine_loop_terminates_with_known_article(tmp_path, monkeypatch):
    monkeypatch.setenv("CLIO_STATE_FILE", str(tmp_path / "state.json"))
    state = run(file='data/article.txt')
    assert bool(state.get('result')), "expected 'result' to be not empty"
    assert bool(state.get('draft')), "expected 'draft' to be not empty"
    assert bool(state.get('review')), "expected 'review' to be not empty"
