"""Step: load_customers (mode=exact)

TAKES: file: str
GIVES: customers: ListType

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import argparse
import json
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", required=True)
    args = parser.parse_args()

    customers = args.file  # echo: TODO replace with real logic

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}
    state["customers"] = customers
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
