"""Step: detect_churn_naive (mode=exact)

TAKES: customers: ListType
GIVES: risks: ListType

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import argparse
import json
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--customers", required=True)
    args = parser.parse_args()

    risks = args.customers  # echo: TODO replace with real logic

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}
    state["risks"] = risks
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
