package flow

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"

	"customer_retention/steps"
)

func Run(ctx context.Context, kwargs map[string]any) (map[string]any, error) {
	state := map[string]any{}

	load_customersOut, err := steps.LoadCustomers(ctx, steps.LoadCustomersIn{ File: "customers.csv" })
	if err != nil {
		return nil, err
	}
	state["customers"] = load_customersOut

	detect_churnOut, err := steps.DetectChurn(ctx, steps.DetectChurnIn{ Customers: state["customers"].(steps.LoadCustomersOut).Customers })
	if err != nil {
		return nil, err
	}
	state["risks"] = detect_churnOut

	return state, nil
}
