"""Module-level helpers for the claude-cli emitter.

These functions and template strings are pure; the emitter class lives
in `clio/emitters/claude_cli.py` and imports from this module.

Some helpers (`_inline_schema`, `_render_prompt`) are also used by the
python emitter (which embeds the claude-cli prompt + schema rendering
to keep cache keys identical across targets). Those are public-ish
across emitters.

Split out per CLAUDE.md scope-discipline rule (~300-line limit per file).
"""

from clio.ir.contracts import type_to_json_schema
from clio.ir.graph import (
    CallIR,
    ContractIR,
    FieldIR,
    ForEachIR,
    HttpServerSpecIR,
    McpServerSpecIR,
    McpToolImplIR,
    SseServerSpecIR,
    StdioServerSpecIR,
    StepIR,
)
from clio.parser.ast_nodes import (
    ConstrainedType,
    ContractRef,
    DictType,
    EnumType,
    ListType,
    PrimitiveType,
    RecordType,
    TypeExpr,
)


def _inline_schema(t: TypeExpr, contracts_by_name: dict[str, ContractIR]) -> dict:
    """Resolve every ContractRef inline. Strips x-clio-assert from inlined contracts
    so the schema is plain JSON Schema (the assert remains on the on-disk version
    used by clio_runtime.validate)."""
    if isinstance(t, ContractRef):
        c = contracts_by_name.get(t.name)
        if c is None:
            return {"$ref": f"../contracts/{t.name}.schema.json"}
        schema = {k: v for k, v in c.json_schema.items() if k != "x-clio-assert"}
        return schema
    if isinstance(t, ListType):
        return {"type": "array", "items": _inline_schema(t.inner, contracts_by_name)}
    if isinstance(t, DictType):
        # v0.21: keys are always `str`. The JSON Schema is a string-keyed
        # object whose value schema is the inlined V type.
        return {
            "type": "object",
            "additionalProperties": _inline_schema(t.value, contracts_by_name),
        }
    if isinstance(t, RecordType):
        return {
            "type": "object",
            "properties": {n: _inline_schema(ty, contracts_by_name) for n, ty in t.fields},
            "required": [n for n, _ in t.fields],
            "additionalProperties": False,
        }
    if isinstance(t, EnumType):
        return {"enum": list(t.values)}
    if isinstance(t, ConstrainedType):
        out = _inline_schema(t.base, contracts_by_name)
        for kind, value in t.constraints:
            if kind == "max":
                out["maxLength"] = value
        return out
    if isinstance(t, PrimitiveType):
        return type_to_json_schema(t)
    return type_to_json_schema(t)


_CLAUDE_MD = """# CLIO-emitted project

Generated from a .clio source by the CLIO compiler v0.1.

This project is self-contained. Run with `bash run.sh` (added at a later phase).
"""


_STEP_NO_FIELDS = '''"""Step: {name} (mode={mode})

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import json
import sys


def main() -> int:
    # TODO: implement step body once TAKES/GIVES are added.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_EXACT_STEP_TEMPLATE = '''"""Step: {name} (mode={mode})

{io_doc}

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import argparse
import json
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
{argparse_block}
    args = parser.parse_args()

    {body}

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {{}}
    state["{out_name}"] = {out_name}
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def emit_rest_step_cli(step, impl, io_doc: str) -> str:
    """Emit a standalone Python script for a claude-cli REST step.

    Each step is run by `bash run.sh` as `python steps/NN_name.py --takes...`
    and reads/writes `state.json` at the repo root. The script imports the
    bundled `clio_runtime.rest` module (templating + retry helpers) by
    adding the parent dir to `sys.path` at startup.
    """
    out_name = step.gives.name if step.gives else "result"
    argparse_lines = [
        f'    parser.add_argument("--{f.name}", required=True)' for f in step.takes
    ] or ["    pass"]

    takes_dict_lines: list[str] = ["    _takes = {"]
    for f in step.takes:
        takes_dict_lines.append(f"        {f.name!r}: args.{f.name},")
    takes_dict_lines.append("    }")
    if not step.takes:
        takes_dict_lines = ["    _takes = {}"]

    kwargs_lines: list[str] = ["    _kwargs: dict = {}"]
    if impl.query is not None:
        kwargs_lines.append(
            f"    _kwargs['params'] = _rest.render_dict({tuple(impl.query)!r}, _takes)"
        )
    headers_seeded = False
    if impl.headers is not None:
        kwargs_lines.append(
            f"    _kwargs['headers'] = _rest.render_dict({tuple(impl.headers)!r}, _takes)"
        )
        headers_seeded = True

    if impl.body is not None:
        body_kind = type(impl.body).__name__
        if body_kind == "JsonBodyIR":
            kwargs_lines.append(
                f"    _kwargs['json'] = _rest.render_dict({tuple(impl.body.fields)!r}, _takes)"
            )
        elif body_kind == "RawBodyIR":
            kwargs_lines.append(
                f"    _kwargs['data'] = _rest.subst({impl.body.template!r}, _takes)"
            )
            if not headers_seeded:
                kwargs_lines.append("    _kwargs.setdefault('headers', {})")
                headers_seeded = True
            kwargs_lines.append(
                "    _kwargs['headers'].setdefault('Content-Type', 'text/plain')"
            )
        elif body_kind == "FileBodyIR":
            kwargs_lines.append(
                f"    _data, _ct = _rest.read_file_body({impl.body.path!r}, _takes)"
            )
            kwargs_lines.append("    _kwargs['data'] = _data")
            if not headers_seeded:
                kwargs_lines.append("    _kwargs.setdefault('headers', {})")
                headers_seeded = True
            kwargs_lines.append("    _kwargs['headers'].setdefault('Content-Type', _ct)")
        elif body_kind == "FormBodyIR":
            kwargs_lines.append(
                f"    _kwargs['data'] = _rest.render_dict({tuple(impl.body.fields)!r}, _takes)"
            )
        elif body_kind == "MultipartBodyIR":
            kwargs_lines += [
                "    _form: dict = {}",
                "    _files: dict = {}",
                f"    for _k, _v in {tuple(impl.body.fields)!r}:",
                "        if isinstance(_v, str) and _v.startswith('@'):",
                "            _path = _v[1:]",
                "            with open(_path, 'rb') as _f:",
                (
                    "                _files[_k] = (Path(_path).name, "
                    "_f.read(), _rest.content_type_for_path(_path))"
                ),
                "        else:",
                (
                    "            _form[_k] = _rest.subst(_v, _takes) "
                    "if isinstance(_v, str) else _v"
                ),
                "    if _form:",
                "        _kwargs['data'] = _form",
                "    if _files:",
                "        _kwargs['files'] = _files",
            ]

    if impl.timeout_seconds is not None:
        kwargs_lines.append(f"    _kwargs['timeout'] = {impl.timeout_seconds}")
    else:
        kwargs_lines.append("    _kwargs['timeout'] = None")

    if impl.retry is not None:
        request_lines = [
            f"    _attempts = {impl.retry.attempts}",
            f"    _retry_on = {tuple(impl.retry.on)!r}",
            f"    _backoff = {impl.retry.backoff!r}",
            f"    _base = {impl.retry.base}",
            f"    _cap = {impl.retry.cap}",
            "    response = None",
            "    for _i in range(_attempts):",
            "        try:",
            f"            response = requests.request(method={impl.method!r}, url=_url, **_kwargs)",
            "        except Exception as _e:",
            "            if _rest.is_retryable_exception(_e, _retry_on) and _i + 1 < _attempts:",
            "                import time as _time",
            "                _time.sleep(_rest.compute_delay(_i + 1, _base, _cap, _backoff))",
            "                continue",
            "            raise",
            "        if (_rest.is_retryable_response(response.status_code, _retry_on)",
            "                and _i + 1 < _attempts):",
            "            _ra = _rest.parse_retry_after(response.headers.get('Retry-After'))",
            "            import time as _time",
            "            _time.sleep(_ra if _ra is not None else _rest.compute_delay(_i + 1, _base, _cap, _backoff))",
            "            continue",
            "        break",
            "    assert response is not None",
        ]
    else:
        request_lines = [
            f"    response = requests.request(method={impl.method!r}, url=_url, **_kwargs)",
        ]

    response_path_repr = repr(impl.response_path)

    body = (
        f'"""Step: {step.name} (exact, impl: rest)\n\n'
        f'{io_doc}\n\n'
        "Auto-generated by clio from `impl: mode: rest`. URL, query, headers,\n"
        "and body string values support ${var} substitution from TAKES and\n"
        "full-value env:NAME resolution. The bundled clio_runtime.rest module\n"
        "(at the output root) provides the templating + retry helpers.\n"
        '"""\n'
        "import argparse\n"
        "import json\n"
        "import re as _re\n"
        "import sys\n"
        "from pathlib import Path\n\n"
        "import requests\n\n"
        "# The compiled output bundles `clio_runtime/rest.py` next to the steps/\n"
        "# directory. Add the output root to sys.path so the import works whatever\n"
        "# the cwd of the bash orchestrator.\n"
        "sys.path.insert(0, str(Path(__file__).resolve().parent.parent))\n"
        "from clio_runtime import rest as _rest  # noqa: E402\n\n\n"
        "STATE_FILE = Path(__file__).resolve().parent.parent / 'state.json'\n\n\n"
        "def _traverse(data, path):\n"
        "    if not path:\n"
        "        return data\n"
        "    for part in _re.findall(r'[^.\\[\\]]+|\\[\\d+\\]', path):\n"
        "        if part.startswith('['):\n"
        "            data = data[int(part[1:-1])]\n"
        "        else:\n"
        "            data = data[part]\n"
        "    return data\n\n\n"
        "def main() -> int:\n"
        "    parser = argparse.ArgumentParser()\n"
        + "\n".join(argparse_lines) + "\n"
        "    args = parser.parse_args()\n"
        + "\n".join(takes_dict_lines) + "\n"
        f"    _url = _rest.subst({impl.url!r}, _takes)\n"
        + "\n".join(kwargs_lines) + "\n"
        + "\n".join(request_lines) + "\n"
        "    response.raise_for_status()\n"
        f"    {out_name} = _traverse(response.json(), {response_path_repr})\n\n"
        "    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}\n"
        f'    state["{out_name}"] = {out_name}\n'
        "    STATE_FILE.write_text(json.dumps(state, indent=2))\n"
        "    return 0\n\n\n"
        "if __name__ == '__main__':\n"
        "    raise SystemExit(main())\n"
    )
    return body


_SHELL_STEP_TEMPLATE = '''"""Step: {name} (exact, impl: shell)

{io_doc}

Auto-generated by clio from `impl: mode: shell`. Argv-style invocation —
no shell pipes/redirections (subprocess.run with shell=False).
TAKES are substituted into argv tokens via ${{var}} placeholders.
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
{argparse_block}
    args = parser.parse_args()
    argv = {argv_repr}
{sub_block}    result = subprocess.run(argv, capture_output=True, text=True, check=True, timeout={timeout_repr})
    {out_name} = result.stdout

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {{}}
    state["{out_name}"] = {out_name}
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_JUDGMENT_PROMPT_TEMPLATE = """You are executing the CLIO step `{name}`.

Input:
{input_block}

Produce a JSON value that EXACTLY matches this schema:
${{schema}}

Rules — these are non-negotiable:
1. Use EXACTLY the property names listed in the schema. Do NOT invent new fields.
2. Every required property must be present in every item.
3. For enum properties, use ONLY values from the listed enum.
4. Respect every constraint (maxLength, etc.).
5. Output the raw JSON value only. No markdown code fences. No prose. No explanation.
"""


def _chain_has_for_each(chain) -> bool:
    """Recursively scan a flow chain for any ForEachIR node."""
    for item in chain:
        if isinstance(item, ForEachIR):
            return True
        # Nested CallIR carries no children; nothing else to recurse into.
    return False


def _flatten_calls(chain) -> list:
    """Recursively yield every CallIR in `chain`, descending into nested
    ForEachIR.body."""
    out: list = []
    for item in chain:
        if isinstance(item, CallIR):
            out.append(item)
        elif isinstance(item, ForEachIR):
            out.extend(_flatten_calls(item.body))
    return out


def _is_primitive_type(t) -> bool:
    """True if `t` is one of int|float|str|bool. Used to decide between
    `jq -r` (primitive → unwrapped) and `jq -c` (object → JSON literal)."""
    if isinstance(t, ConstrainedType):
        return _is_primitive_type(t.base)
    return isinstance(t, PrimitiveType)


def _resolve_iter_inner_type(t):
    """Return the element type of a ListType, or None for any other shape."""
    return t.inner if isinstance(t, ListType) else None


def _render_prompt(step: StepIR) -> str:
    input_block = "\n".join(f"  {f.name}: ${{{f.name}}}" for f in step.takes) or "  (no inputs)"
    return _JUDGMENT_PROMPT_TEMPLATE.format(name=step.name, input_block=input_block)


def _field_doc(f: FieldIR) -> str:
    return f"TAKES: {f.name}: {_render_type(f.type)}"


def _render_type(t) -> str:
    if isinstance(t, PrimitiveType):
        return t.name
    return type(t).__name__


def _server_spec_dict_repr_cli(spec: McpServerSpecIR) -> str:
    """Render an `McpServerSpecIR` as a Python dict literal usable in
    emitted claude-cli step scripts. Mirrors the python-target helper."""
    if isinstance(spec, StdioServerSpecIR):
        return (
            "{"
            f"'name': {spec.name!r}, "
            f"'transport': 'stdio', "
            f"'command': {spec.command!r}, "
            f"'args': {list(spec.args)!r}, "
            f"'env': {list(spec.env)!r}"
            "}"
        )
    if isinstance(spec, SseServerSpecIR):
        return (
            "{"
            f"'name': {spec.name!r}, "
            f"'transport': 'sse', "
            f"'url': {spec.url!r}, "
            f"'headers': {list(spec.headers)!r}"
            "}"
        )
    if isinstance(spec, HttpServerSpecIR):
        return (
            "{"
            f"'name': {spec.name!r}, "
            f"'transport': 'http', "
            f"'url': {spec.url!r}, "
            f"'headers': {list(spec.headers)!r}"
            "}"
        )
    raise ValueError(f"unknown McpServerSpecIR subtype: {type(spec).__name__}")


def emit_mcp_tool_step_cli(
    step: StepIR,
    impl: McpToolImplIR,
    spec: McpServerSpecIR,
    io_doc: str,
) -> str:
    """Emit a standalone Python script for a claude-cli mcp_tool step.

    Each step is run by `bash run.sh` as `python steps/NN_name.py --takes...`.
    The script boots an MCP client (per-step — claude-cli has no place to
    hold a long-lived client across subprocess invocations), calls the
    requested tool, writes the result into `state.json`, then exits.
    """
    out_name = step.gives.name if step.gives else "result"
    argparse_lines = [
        f'    parser.add_argument("--{f.name}", required=True)' for f in step.takes
    ] or ["    pass"]

    takes_dict_lines: list[str] = ["    _takes = {"]
    for f in step.takes:
        takes_dict_lines.append(f"        {f.name!r}: args.{f.name},")
    takes_dict_lines.append("    }")
    if not step.takes:
        takes_dict_lines = ["    _takes = {}"]

    server_repr = _server_spec_dict_repr_cli(spec)
    args_repr = "{" + ", ".join(f"{k!r}: {v!r}" for k, v in impl.args) + "}"

    body = (
        f'"""Step: {step.name} (exact, impl: mcp_tool)\n\n'
        f'{io_doc}\n\n'
        "Auto-generated by clio from `impl: mode: mcp_tool`. The bundled\n"
        "clio_runtime.mcp_client module provides the client + transport\n"
        "handling. Each step boots a per-call client (claude-cli has no\n"
        "long-lived orchestrator).\n"
        '"""\n'
        "import argparse\n"
        "import asyncio\n"
        "import json\n"
        "import sys\n"
        "from pathlib import Path\n\n"
        "# The compiled output bundles `clio_runtime/mcp_client.py` next to the\n"
        "# steps/ directory. Add the output root to sys.path so the import works\n"
        "# whatever the cwd of the bash orchestrator.\n"
        "sys.path.insert(0, str(Path(__file__).resolve().parent.parent))\n"
        "from clio_runtime import mcp_client as _mcp  # noqa: E402\n\n\n"
        "STATE_FILE = Path(__file__).resolve().parent.parent / 'state.json'\n\n\n"
        "def main() -> int:\n"
        "    parser = argparse.ArgumentParser()\n"
        + "\n".join(argparse_lines) + "\n"
        "    args = parser.parse_args()\n"
        + "\n".join(takes_dict_lines) + "\n"
        f"    _server = {server_repr}\n"
        f"    _args = {args_repr}\n"
        f"    {out_name} = asyncio.run(_mcp.call_tool_async(\n"
        f"        _server, {impl.tool!r}, _args, _takes,\n"
        f"        timeout={impl.timeout_seconds}, parse={impl.parse!r},\n"
        f"    ))\n\n"
        "    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}\n"
        f'    state["{out_name}"] = {out_name}\n'
        "    STATE_FILE.write_text(json.dumps(state, indent=2))\n"
        "    return 0\n\n\n"
        "if __name__ == '__main__':\n"
        "    raise SystemExit(main())\n"
    )
    return body
