"""Module-level helpers for the claude-cli emitter.

These functions and template strings are pure; the emitter class lives
in `clio/emitters/claude_cli.py` and imports from this module.

Some helpers (`_inline_schema`, `_render_prompt`) are also used by the
python emitter (which embeds the claude-cli prompt + schema rendering
to keep cache keys identical across targets). Those are public-ish
across emitters.

Split out per CLAUDE.md scope-discipline rule (~300-line limit per file).
"""

from clio.ir.contracts import type_to_json_schema
from clio.ir.graph import (
    CallIR,
    ContractIR,
    FieldIR,
    ForEachIR,
    StepIR,
)
from clio.parser.ast_nodes import (
    ConstrainedType,
    ContractRef,
    EnumType,
    ListType,
    PrimitiveType,
    RecordType,
    TypeExpr,
)


def _inline_schema(t: TypeExpr, contracts_by_name: dict[str, ContractIR]) -> dict:
    """Resolve every ContractRef inline. Strips x-clio-assert from inlined contracts
    so the schema is plain JSON Schema (the assert remains on the on-disk version
    used by clio_runtime.validate)."""
    if isinstance(t, ContractRef):
        c = contracts_by_name.get(t.name)
        if c is None:
            return {"$ref": f"../contracts/{t.name}.schema.json"}
        schema = {k: v for k, v in c.json_schema.items() if k != "x-clio-assert"}
        return schema
    if isinstance(t, ListType):
        return {"type": "array", "items": _inline_schema(t.inner, contracts_by_name)}
    if isinstance(t, RecordType):
        return {
            "type": "object",
            "properties": {n: _inline_schema(ty, contracts_by_name) for n, ty in t.fields},
            "required": [n for n, _ in t.fields],
            "additionalProperties": False,
        }
    if isinstance(t, EnumType):
        return {"enum": list(t.values)}
    if isinstance(t, ConstrainedType):
        out = _inline_schema(t.base, contracts_by_name)
        for kind, value in t.constraints:
            if kind == "max":
                out["maxLength"] = value
        return out
    if isinstance(t, PrimitiveType):
        return type_to_json_schema(t)
    return type_to_json_schema(t)


_CLAUDE_MD = """# CLIO-emitted project

Generated from a .clio source by the CLIO compiler v0.1.

This project is self-contained. Run with `bash run.sh` (added at a later phase).
"""


_STEP_NO_FIELDS = '''"""Step: {name} (mode={mode})

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import json
import sys


def main() -> int:
    # TODO: implement step body once TAKES/GIVES are added.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_EXACT_STEP_TEMPLATE = '''"""Step: {name} (mode={mode})

{io_doc}

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import argparse
import json
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
{argparse_block}
    args = parser.parse_args()

    {body}

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {{}}
    state["{out_name}"] = {out_name}
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_REST_STEP_TEMPLATE = '''"""Step: {name} (exact, impl: rest)

{io_doc}

Auto-generated by clio from `impl: mode: rest`. Requires `requests`
to be installed in the environment that runs `bash run.sh`.

v0.2 limitations:
- TAKES are accepted in argparse for orchestrator parity but not yet
  templated into the URL/headers/body.
- retries is parsed but not honored at runtime.
"""

import argparse
import json
import re as _re
import sys
from pathlib import Path

import requests


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def _traverse(data, path):
    if not path:
        return data
    for part in _re.findall(r'[^.\\[\\]]+|\\[\\d+\\]', path):
        if part.startswith('['):
            data = data[int(part[1:-1])]
        else:
            data = data[part]
    return data


def main() -> int:
    parser = argparse.ArgumentParser()
{argparse_block}
    args = parser.parse_args()
{unused_takes}
    response = requests.request(
        method={method!r},
        url={url!r},
        timeout={timeout_repr},
    )
    response.raise_for_status()
    {out_name} = _traverse(response.json(), {response_path_repr})

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {{}}
    state["{out_name}"] = {out_name}
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_JUDGMENT_PROMPT_TEMPLATE = """You are executing the CLIO step `{name}`.

Input:
{input_block}

Produce a JSON value that EXACTLY matches this schema:
${{schema}}

Rules — these are non-negotiable:
1. Use EXACTLY the property names listed in the schema. Do NOT invent new fields.
2. Every required property must be present in every item.
3. For enum properties, use ONLY values from the listed enum.
4. Respect every constraint (maxLength, etc.).
5. Output the raw JSON value only. No markdown code fences. No prose. No explanation.
"""


def _chain_has_for_each(chain) -> bool:
    """Recursively scan a flow chain for any ForEachIR node."""
    for item in chain:
        if isinstance(item, ForEachIR):
            return True
        # Nested CallIR carries no children; nothing else to recurse into.
    return False


def _flatten_calls(chain) -> list:
    """Recursively yield every CallIR in `chain`, descending into nested
    ForEachIR.body."""
    out: list = []
    for item in chain:
        if isinstance(item, CallIR):
            out.append(item)
        elif isinstance(item, ForEachIR):
            out.extend(_flatten_calls(item.body))
    return out


def _is_primitive_type(t) -> bool:
    """True if `t` is one of int|float|str|bool. Used to decide between
    `jq -r` (primitive → unwrapped) and `jq -c` (object → JSON literal)."""
    if isinstance(t, ConstrainedType):
        return _is_primitive_type(t.base)
    return isinstance(t, PrimitiveType)


def _resolve_iter_inner_type(t):
    """Return the element type of a ListType, or None for any other shape."""
    return t.inner if isinstance(t, ListType) else None


def _render_prompt(step: StepIR) -> str:
    input_block = "\n".join(f"  {f.name}: ${{{f.name}}}" for f in step.takes) or "  (no inputs)"
    return _JUDGMENT_PROMPT_TEMPLATE.format(name=step.name, input_block=input_block)


def _field_doc(f: FieldIR) -> str:
    return f"TAKES: {f.name}: {_render_type(f.type)}"


def _render_type(t) -> str:
    if isinstance(t, PrimitiveType):
        return t.name
    return type(t).__name__
