"""Static Go runtime templates emitted under <output>/clio_runtime/.

These are pure Go source strings: no per-graph substitution, no Python
imports beyond what the template body uses. Each template's nullary
renderer (e.g. render_clio_runtime_validate) returns the string verbatim.

Why a separate module: keeps clio/emitters/_go_helpers.py focused on
graph-bound rendering (per-FLOW dispatch logic) and lets the embedded
Go source live next to other static templates rather than interleaved
with helper functions. Matches the layout pattern python emitter uses
when it copies clio/runtime/*.py verbatim.
"""
from __future__ import annotations

_VALIDATE_GO_TEMPLATE = """package validate

// Auto-generated by CLIO. Do not edit by hand.

import (
\t"context"
\t"encoding/json"
\t"fmt"

\t"github.com/santhosh-tekuri/jsonschema/v6"
)

// Schema validates `instance` against the given JSON Schema string.
// Also evaluates an x-clio-assert clause if present (CLIO's compact assert AST).
func Schema(ctx context.Context, schemaJSON string, instance any) error {
\tvar raw any
\tif err := json.Unmarshal([]byte(schemaJSON), &raw); err != nil {
\t\treturn fmt.Errorf("validate: invalid schema JSON: %w", err)
\t}
\tcompiler := jsonschema.NewCompiler()
\tif err := compiler.AddResource("file:///schema.json", raw); err != nil {
\t\treturn fmt.Errorf("validate: add schema: %w", err)
\t}
\tsch, err := compiler.Compile("file:///schema.json")
\tif err != nil {
\t\treturn fmt.Errorf("validate: compile schema: %w", err)
\t}
\tif err := sch.Validate(instance); err != nil {
\t\treturn fmt.Errorf("validate: schema: %w", err)
\t}
\tif m, ok := raw.(map[string]any); ok {
\t\tif assertNode, ok := m["x-clio-assert"]; ok {
\t\t\tif !evalAssert(assertNode, instance) {
\t\t\t\treturn fmt.Errorf("validate: x-clio-assert failed")
\t\t\t}
\t\t}
\t}
\treturn nil
}

// evalAssert walks the compact CLIO assert AST. Node kinds: ident, int, float,
// str, call(len, ...), compare(==,!=,<,>,<=,>=). Any other kind is treated as
// false (defensive). The walker is a direct port of clio/runtime/validate.py.
func evalAssert(node any, ctx any) bool {
\tm, ok := node.(map[string]any)
\tif !ok {
\t\treturn false
\t}
\tkind, _ := m["kind"].(string)
\tswitch kind {
\tcase "ident":
\t\t// Resolve from ctx (must be a map[string]any in this codebase).
\t\tif obj, ok := ctx.(map[string]any); ok {
\t\t\t_, ok := obj[m["name"].(string)]
\t\t\treturn ok
\t\t}
\t\treturn false
\tcase "int", "float", "str":
\t\treturn true
\tcase "call":
\t\tfn, _ := m["func"].(string)
\t\tif fn != "len" {
\t\t\treturn false
\t\t}
\t\targs, _ := m["args"].([]any)
\t\tif len(args) != 1 {
\t\t\treturn false
\t\t}
\t\treturn lenOf(args[0], ctx) >= 0
\tcase "compare":
\t\tleft := resolve(m["left"], ctx)
\t\tright := resolve(m["right"], ctx)
\t\top, _ := m["op"].(string)
\t\treturn cmpOk(left, right, op)
\t}
\treturn false
}

func resolve(node any, ctx any) any {
\tm, _ := node.(map[string]any)
\tswitch m["kind"] {
\tcase "ident":
\t\tif obj, ok := ctx.(map[string]any); ok {
\t\t\treturn obj[m["name"].(string)]
\t\t}
\t\treturn nil
\tcase "int":
\t\treturn int64(m["value"].(float64))
\tcase "float":
\t\treturn m["value"]
\tcase "str":
\t\treturn m["value"]
\tcase "call":
\t\t// Only len() is supported today; mirror evalAssert's guard.
\t\tif fn, _ := m["func"].(string); fn != "len" {
\t\t\treturn nil
\t\t}
\t\treturn lenOf(m["args"].([]any)[0], ctx)
\t}
\treturn nil
}

func lenOf(node any, ctx any) int64 {
\tv := resolve(node, ctx)
\tswitch s := v.(type) {
\tcase string:
\t\treturn int64(len(s))
\tcase []any:
\t\treturn int64(len(s))
\tcase map[string]any:
\t\treturn int64(len(s))
\t}
\treturn -1
}

func cmpOk(l, r any, op string) bool {
\tlf, lok := toFloat(l)
\trf, rok := toFloat(r)
\tif lok && rok {
\t\tswitch op {
\t\tcase "==":
\t\t\treturn lf == rf
\t\tcase "!=":
\t\t\treturn lf != rf
\t\tcase "<":
\t\t\treturn lf < rf
\t\tcase ">":
\t\t\treturn lf > rf
\t\tcase "<=":
\t\t\treturn lf <= rf
\t\tcase ">=":
\t\t\treturn lf >= rf
\t\t}
\t}
\tls, lsOk := l.(string)
\trs, rsOk := r.(string)
\tif lsOk && rsOk {
\t\tswitch op {
\t\tcase "==":
\t\t\treturn ls == rs
\t\tcase "!=":
\t\t\treturn ls != rs
\t\t}
\t}
\treturn false
}

func toFloat(v any) (float64, bool) {
\tswitch n := v.(type) {
\tcase int64:
\t\treturn float64(n), true
\tcase float64:
\t\treturn n, true
\t}
\treturn 0, false
}
"""


def render_clio_runtime_validate() -> str:
    """Return the body of <output>/clio_runtime/validate/validate.go.

    Static template — no per-emission substitution required. Emitted only
    when the flow uses at least one contract."""
    return _VALIDATE_GO_TEMPLATE


_CACHE_GO_TEMPLATE = '''package cache

// Auto-generated by CLIO. Cache layout matches clio/runtime/cache.py
// byte-for-byte so cache files are interchangeable with the python target.
//
// On disk: <cache_dir>/<step_name>/<sha256>.json
//   {"created_at": <epoch>, "model": "<m>", "response": "<raw>"}

import (
\t"crypto/sha256"
\t"encoding/hex"
\t"encoding/json"
\t"os"
\t"path/filepath"
\t"strings"
\t"time"
)

// Key derives the cache key. Identical formula to clio/runtime/cache.py:
// SHA256(step + "\\n" + model + "\\n" + prompt + "\\n" + schemaJSON).
func Key(step, model, prompt, schemaJSON string) string {
\tpayload := strings.Join([]string{step, model, prompt, schemaJSON}, "\\n")
\tsum := sha256.Sum256([]byte(payload))
\treturn hex.EncodeToString(sum[:])
}

// Lookup returns (response, true) if the cache entry is present and fresh.
// ttlSeconds: nil for permanent (CACHE: on), 0 to skip, positive for ttl.
func Lookup(cacheDir, stepName, key string, ttlSeconds *int64) (string, bool) {
\tif ttlSeconds != nil && *ttlSeconds == 0 {
\t\treturn "", false
\t}
\tpath := filepath.Join(cacheDir, stepName, key+".json")
\traw, err := os.ReadFile(path)
\tif err != nil {
\t\treturn "", false
\t}
\tvar entry struct {
\t\tCreatedAt int64  `json:"created_at"`
\t\tModel     string `json:"model"`
\t\tResponse  string `json:"response"`
\t}
\tif err := json.Unmarshal(raw, &entry); err != nil {
\t\treturn "", false
\t}
\tif ttlSeconds != nil {
\t\tif time.Now().Unix()-entry.CreatedAt >= *ttlSeconds {
\t\t\treturn "", false
\t\t}
\t}
\treturn entry.Response, true
}

// Store writes a cache entry atomically.
func Store(cacheDir, stepName, key, model, response string) error {
\tdir := filepath.Join(cacheDir, stepName)
\tif err := os.MkdirAll(dir, 0o755); err != nil {
\t\treturn err
\t}
\tentry := map[string]any{
\t\t"created_at": time.Now().Unix(),
\t\t"model":      model,
\t\t"response":   response,
\t}
\tbody, err := json.Marshal(entry)
\tif err != nil {
\t\treturn err
\t}
\ttmp := filepath.Join(dir, key+".json.tmp")
\tif err := os.WriteFile(tmp, body, 0o644); err != nil {
\t\treturn err
\t}
\tfinal := filepath.Join(dir, key+".json")
\treturn os.Rename(tmp, final)
}

// CacheDirFromEnv returns CLIO_CACHE_DIR or the relative path ".cache".
// Mirrors the python emitter's clio/emitters/python.py fallback so both
// targets resolve the cache directory relative to the same CWD.
func CacheDirFromEnv() string {
\tif d := os.Getenv("CLIO_CACHE_DIR"); d != "" {
\t\treturn d
\t}
\treturn ".cache"
}
'''


def render_clio_runtime_cache() -> str:
    """Return the body of <output>/clio_runtime/cache/cache.go.

    Static template — no per-emission substitution. Emitted only when
    the entry flow has >=1 step with a CACHE directive."""
    return _CACHE_GO_TEMPLATE


_SUBSTITUTE_GO_TEMPLATE = '''package substitute

// Auto-generated by CLIO. Mirrors clio/runtime/rest.py::subst so REST and
// shell steps interpolate ${var} / resolve env:NAME identically across targets.

import (
\t"fmt"
\t"os"
\t"regexp"
)

var (
\tplaceholderRe = regexp.MustCompile(`\\$\\{([a-zA-Z_][a-zA-Z0-9_]*)\\}`)
\tenvWholeRe    = regexp.MustCompile(`^env:([A-Z_][A-Z0-9_]*)$`)
)

// Apply substitutes ${var} placeholders from `takes` and resolves a whole-string
// `env:NAME` against the process environment. Inline `env:` (not the whole string)
// is treated as plain text. Returns an error when a referenced var is absent from
// `takes` or a referenced env var is unset (parity with rest.py\'s KeyError).
func Apply(token string, takes map[string]any) (string, error) {
\tif m := envWholeRe.FindStringSubmatch(token); m != nil {
\t\tname := m[1]
\t\tv, ok := os.LookupEnv(name)
\t\tif !ok {
\t\t\treturn "", fmt.Errorf("impl.rest: env var %q is not set", name)
\t\t}
\t\treturn v, nil
\t}
\tvar subErr error
\tout := placeholderRe.ReplaceAllStringFunc(token, func(match string) string {
\t\tkey := placeholderRe.FindStringSubmatch(match)[1]
\t\tv, ok := takes[key]
\t\tif !ok {
\t\t\tif subErr == nil {
\t\t\t\tsubErr = fmt.Errorf("impl.rest: ${%s} not found in TAKES", key)
\t\t\t}
\t\t\treturn match
\t\t}
\t\treturn fmt.Sprintf("%v", v)
\t})
\tif subErr != nil {
\t\treturn "", subErr
\t}
\treturn out, nil
}
'''


def render_clio_runtime_substitute() -> str:
    """Return the body of <output>/clio_runtime/substitute/substitute.go.

    Static template — no per-emission substitution. Emitted only when the flow
    has >=1 REST (or, from Phase 2, shell) step. Shared `${var}` / `env:NAME`
    helper mirroring clio/runtime/rest.py::subst."""
    return _SUBSTITUTE_GO_TEMPLATE


_REST_GO_TEMPLATE = '''package rest

// Auto-generated by CLIO. Retry classification + backoff mirror
// clio/runtime/rest.py byte-for-behaviour so a .clio REST step behaves
// identically on the python and go targets.

import (
\t"errors"
\t"net"
\t"net/url"
\t"strconv"
\t"time"

\t"{pkg}/clio_runtime/substitute"
)

// Subst delegates ${{var}} / env:NAME interpolation to the shared substitute pkg.
func Subst(template string, takes map[string]any) (string, error) {{
\treturn substitute.Apply(template, takes)
}}

// RenderDict substitutes string values via Subst; non-string scalars pass through.
// Mirrors clio/runtime/rest.py::render_dict.
func RenderDict(items map[string]any, takes map[string]any) (map[string]any, error) {{
\tout := make(map[string]any, len(items))
\tfor k, v := range items {{
\t\tif s, ok := v.(string); ok {{
\t\t\tr, err := Subst(s, takes)
\t\t\tif err != nil {{
\t\t\t\treturn nil, err
\t\t\t}}
\t\t\tout[k] = r
\t\t}} else {{
\t\t\tout[k] = v
\t\t}}
\t}}
\treturn out, nil
}}

// IsRetryableStatus mirrors clio/runtime/rest.py::is_retryable_response.
func IsRetryableStatus(code int, on []string) bool {{
\tfor _, o := range on {{
\t\tif o == "5xx" && code >= 500 && code < 600 {{
\t\t\treturn true
\t\t}}
\t\tif o == "429" && code == 429 {{
\t\t\treturn true
\t\t}}
\t}}
\treturn false
}}

// IsRetryableErr mirrors clio/runtime/rest.py::is_retryable_exception using the
// Go stdlib: a net.Error with Timeout() classifies as "timeout"; any other
// transport-level url.Error classifies as "network".
func IsRetryableErr(err error, on []string) bool {{
\tif err == nil {{
\t\treturn false
\t}}
\tvar netErr net.Error
\tisTimeout := errors.As(err, &netErr) && netErr.Timeout()
\tfor _, o := range on {{
\t\tif o == "timeout" && isTimeout {{
\t\t\treturn true
\t\t}}
\t}}
\tvar urlErr *url.Error
\tif errors.As(err, &urlErr) && !isTimeout {{
\t\tfor _, o := range on {{
\t\t\tif o == "network" {{
\t\t\t\treturn true
\t\t\t}}
\t\t}}
\t}}
\treturn false
}}

// ComputeDelay mirrors clio/runtime/rest.py::compute_delay (attempt 1-indexed).
func ComputeDelay(attempt int, base, cap float64, backoff string) time.Duration {{
\tvar secs float64
\tif backoff == "constant" {{
\t\tsecs = base
\t}} else {{
\t\tsecs = base * float64(int64(1)<<uint(attempt-1))
\t}}
\tif secs > cap {{
\t\tsecs = cap
\t}}
\treturn time.Duration(secs * float64(time.Second))
}}

// ParseRetryAfter parses a seconds-only Retry-After header (HTTP-date unsupported,
// matching clio/runtime/rest.py::parse_retry_after). Returns (delay, true) on a
// valid non-negative number; negatives clamp to zero.
func ParseRetryAfter(v string) (time.Duration, bool) {{
\tif v == "" {{
\t\treturn 0, false
\t}}
\tf, err := strconv.ParseFloat(v, 64)
\tif err != nil {{
\t\treturn 0, false
\t}}
\tif f < 0 {{
\t\tf = 0
\t}}
\treturn time.Duration(f * float64(time.Second)), true
}}
'''


def render_clio_runtime_rest(pkg: str) -> str:
    """Return the body of <output>/clio_runtime/rest/rest.go.

    `pkg` is the emitted module name so the embedded import of the shared
    substitute package resolves. Emitted only when the flow has >=1 REST step.
    Retry classification + backoff mirror clio/runtime/rest.py."""
    return _REST_GO_TEMPLATE.format(pkg=pkg)
