"""Static Go runtime templates emitted under <output>/clio_runtime/.

These are pure Go source strings: no per-graph substitution, no Python
imports beyond what the template body uses. Each template's nullary
renderer (e.g. render_clio_runtime_validate) returns the string verbatim.

Why a separate module: keeps clio/emitters/_go_helpers.py focused on
graph-bound rendering (per-FLOW dispatch logic) and lets the embedded
Go source live next to other static templates rather than interleaved
with helper functions. Matches the layout pattern python emitter uses
when it copies clio/runtime/*.py verbatim.
"""
from __future__ import annotations

_VALIDATE_GO_TEMPLATE = """package validate

// Auto-generated by CLIO. Do not edit by hand.

import (
\t"context"
\t"encoding/json"
\t"fmt"

\t"github.com/santhosh-tekuri/jsonschema/v6"
)

// Schema validates `instance` against the given JSON Schema string.
// Also evaluates an x-clio-assert clause if present (CLIO's compact assert AST).
func Schema(ctx context.Context, schemaJSON string, instance any) error {
\tvar raw any
\tif err := json.Unmarshal([]byte(schemaJSON), &raw); err != nil {
\t\treturn fmt.Errorf("validate: invalid schema JSON: %w", err)
\t}
\tcompiler := jsonschema.NewCompiler()
\tif err := compiler.AddResource("file:///schema.json", raw); err != nil {
\t\treturn fmt.Errorf("validate: add schema: %w", err)
\t}
\tsch, err := compiler.Compile("file:///schema.json")
\tif err != nil {
\t\treturn fmt.Errorf("validate: compile schema: %w", err)
\t}
\tif err := sch.Validate(instance); err != nil {
\t\treturn fmt.Errorf("validate: schema: %w", err)
\t}
\tif m, ok := raw.(map[string]any); ok {
\t\tif assertNode, ok := m["x-clio-assert"]; ok {
\t\t\tif !evalAssert(assertNode, instance) {
\t\t\t\treturn fmt.Errorf("validate: x-clio-assert failed")
\t\t\t}
\t\t}
\t}
\treturn nil
}

// evalAssert walks the compact CLIO assert AST. Node kinds: ident, int, float,
// str, call(len, ...), compare(==,!=,<,>,<=,>=). Any other kind is treated as
// false (defensive). The walker is a direct port of clio/runtime/validate.py.
func evalAssert(node any, ctx any) bool {
\tm, ok := node.(map[string]any)
\tif !ok {
\t\treturn false
\t}
\tkind, _ := m["kind"].(string)
\tswitch kind {
\tcase "ident":
\t\t// Resolve from ctx (must be a map[string]any in this codebase).
\t\tif obj, ok := ctx.(map[string]any); ok {
\t\t\t_, ok := obj[m["name"].(string)]
\t\t\treturn ok
\t\t}
\t\treturn false
\tcase "int", "float", "str":
\t\treturn true
\tcase "call":
\t\tfn, _ := m["func"].(string)
\t\tif fn != "len" {
\t\t\treturn false
\t\t}
\t\targs, _ := m["args"].([]any)
\t\tif len(args) != 1 {
\t\t\treturn false
\t\t}
\t\treturn lenOf(args[0], ctx) >= 0
\tcase "compare":
\t\tleft := resolve(m["left"], ctx)
\t\tright := resolve(m["right"], ctx)
\t\top, _ := m["op"].(string)
\t\treturn cmpOk(left, right, op)
\t}
\treturn false
}

func resolve(node any, ctx any) any {
\tm, _ := node.(map[string]any)
\tswitch m["kind"] {
\tcase "ident":
\t\tif obj, ok := ctx.(map[string]any); ok {
\t\t\treturn obj[m["name"].(string)]
\t\t}
\t\treturn nil
\tcase "int":
\t\treturn int64(m["value"].(float64))
\tcase "float":
\t\treturn m["value"]
\tcase "str":
\t\treturn m["value"]
\tcase "call":
\t\t// Only len() is supported today; mirror evalAssert's guard.
\t\tif fn, _ := m["func"].(string); fn != "len" {
\t\t\treturn nil
\t\t}
\t\treturn lenOf(m["args"].([]any)[0], ctx)
\t}
\treturn nil
}

func lenOf(node any, ctx any) int64 {
\tv := resolve(node, ctx)
\tswitch s := v.(type) {
\tcase string:
\t\treturn int64(len(s))
\tcase []any:
\t\treturn int64(len(s))
\tcase map[string]any:
\t\treturn int64(len(s))
\t}
\treturn -1
}

func cmpOk(l, r any, op string) bool {
\tlf, lok := toFloat(l)
\trf, rok := toFloat(r)
\tif lok && rok {
\t\tswitch op {
\t\tcase "==":
\t\t\treturn lf == rf
\t\tcase "!=":
\t\t\treturn lf != rf
\t\tcase "<":
\t\t\treturn lf < rf
\t\tcase ">":
\t\t\treturn lf > rf
\t\tcase "<=":
\t\t\treturn lf <= rf
\t\tcase ">=":
\t\t\treturn lf >= rf
\t\t}
\t}
\tls, lsOk := l.(string)
\trs, rsOk := r.(string)
\tif lsOk && rsOk {
\t\tswitch op {
\t\tcase "==":
\t\t\treturn ls == rs
\t\tcase "!=":
\t\t\treturn ls != rs
\t\t}
\t}
\treturn false
}

func toFloat(v any) (float64, bool) {
\tswitch n := v.(type) {
\tcase int64:
\t\treturn float64(n), true
\tcase float64:
\t\treturn n, true
\t}
\treturn 0, false
}
"""


def render_clio_runtime_validate() -> str:
    """Return the body of <output>/clio_runtime/validate/validate.go.

    Static template — no per-emission substitution required. Emitted only
    when the flow uses at least one contract."""
    return _VALIDATE_GO_TEMPLATE


_CACHE_GO_TEMPLATE = '''package cache

// Auto-generated by CLIO. Cache layout matches clio/runtime/cache.py
// byte-for-byte so cache files are interchangeable with the python target.
//
// On disk: <cache_dir>/<step_name>/<sha256>.json
//   {"created_at": <epoch>, "model": "<m>", "response": "<raw>"}

import (
\t"crypto/sha256"
\t"encoding/hex"
\t"encoding/json"
\t"fmt"
\t"os"
\t"path/filepath"
\t"strings"
\t"time"
)

// Key derives the cache key. Identical formula to clio/runtime/cache.py:
// SHA256(step + "\\n" + model + "\\n" + prompt + "\\n" + schemaJSON).
func Key(step, model, prompt, schemaJSON string) string {
\tpayload := strings.Join([]string{step, model, prompt, schemaJSON}, "\\n")
\tsum := sha256.Sum256([]byte(payload))
\treturn hex.EncodeToString(sum[:])
}

// Lookup returns (response, true) if the cache entry is present and fresh.
// ttlSeconds: nil for permanent (CACHE: on), 0 to skip, positive for ttl.
func Lookup(cacheDir, stepName, key string, ttlSeconds *int64) (string, bool) {
\tif ttlSeconds != nil && *ttlSeconds == 0 {
\t\treturn "", false
\t}
\tpath := filepath.Join(cacheDir, stepName, key+".json")
\traw, err := os.ReadFile(path)
\tif err != nil {
\t\treturn "", false
\t}
\tvar entry struct {
\t\tCreatedAt int64  `json:"created_at"`
\t\tModel     string `json:"model"`
\t\tResponse  string `json:"response"`
\t}
\tif err := json.Unmarshal(raw, &entry); err != nil {
\t\treturn "", false
\t}
\tif ttlSeconds != nil {
\t\tif time.Now().Unix()-entry.CreatedAt >= *ttlSeconds {
\t\t\treturn "", false
\t\t}
\t}
\treturn entry.Response, true
}

// Store writes a cache entry atomically.
func Store(cacheDir, stepName, key, model, response string) error {
\tdir := filepath.Join(cacheDir, stepName)
\tif err := os.MkdirAll(dir, 0o755); err != nil {
\t\treturn err
\t}
\tentry := map[string]any{
\t\t"created_at": time.Now().Unix(),
\t\t"model":      model,
\t\t"response":   response,
\t}
\tbody, err := json.Marshal(entry)
\tif err != nil {
\t\treturn err
\t}
\ttmp := filepath.Join(dir, key+".json.tmp")
\tif err := os.WriteFile(tmp, body, 0o644); err != nil {
\t\treturn err
\t}
\tfinal := filepath.Join(dir, key+".json")
\treturn os.Rename(tmp, final)
}

// CacheDirFromEnv returns CLIO_CACHE_DIR or "<cwd>/.cache".
func CacheDirFromEnv() string {
\tif d := os.Getenv("CLIO_CACHE_DIR"); d != "" {
\t\treturn d
\t}
\tcwd, _ := os.Getwd()
\treturn fmt.Sprintf("%s/.cache", cwd)
}
'''


def render_clio_runtime_cache() -> str:
    """Return the body of <output>/clio_runtime/cache/cache.go.

    Static template — no per-emission substitution. Emitted only when
    the entry flow has >=1 step with a CACHE directive."""
    return _CACHE_GO_TEMPLATE
