"""Renderer for the top-level flow orchestrator (`flow/flow.go`).

Emits `func Run(ctx, kwargs) (state, error)` that chains every CallIR in
graph.flow.chain. v0.20.0 scope: sequential chain only; T12-T15 will
extend this module with IF/MATCH/WHILE/FOR EACH emission.
"""
from __future__ import annotations

from clio.emitters._go_helpers import _go_module_name
from clio.emitters._shared_utils import _to_class_name, _to_go_field_name, _type_to_go
from clio.ir.graph import CallIR, ContractIR, FlowGraph, StepIR


def _kwargs_to_step_input(
    step: StepIR,
    prev_state_var: str,
    contracts: dict[str, ContractIR],
) -> str:
    """Render the literal `<Step>In{...}` initialisation pulling fields from
    kwargs (first step) or the previous step's typed output (subsequent steps).

    v0.20.0 assumes 1:1 GIVES/TAKES field name alignment between adjacent
    steps. If a later spec adds explicit field remapping at chain time,
    revisit here.
    """
    cls = _to_class_name(step.name)
    parts: list[str] = []
    for field in step.takes:
        gf = _to_go_field_name(field.name)
        if prev_state_var == "kwargs":
            parts.append(
                f'{gf}: {prev_state_var}["{field.name}"].'
                f'({_type_to_go(field.type, contracts)})'
            )
        else:
            parts.append(f"{gf}: {prev_state_var}.{gf}")
    return f"steps.{cls}In{{ {', '.join(parts)} }}"


def render_flow_go(graph: FlowGraph) -> str:
    """Render flow/flow.go — top-level orchestrator (sequential chain only)."""
    pkg = _go_module_name(graph)  # NOT _safe_package_name — Go requires lowercase
    if graph.flow is None:
        # No entry flow — emit an empty orchestrator. T19 should reject earlier.
        return (
            "package flow\n\n"
            "// Auto-generated by CLIO.\n\n"
            "import \"context\"\n\n"
            "func Run(ctx context.Context, kwargs map[string]any) "
            "(map[string]any, error) {\n"
            "\treturn map[string]any{}, nil\n"
            "}\n"
        )

    contracts_by_name = {c.name: c for c in graph.contracts}
    steps_by_name = {s.name: s for s in graph.steps if isinstance(s, StepIR)}

    lines: list[str] = [
        "package flow",
        "",
        "// Auto-generated by CLIO. Do not edit by hand.",
        "",
        "import (",
        '\t"context"',
        "",
        f'\t"{pkg}/steps"',
        ")",
        "",
        "func Run(ctx context.Context, kwargs map[string]any) (map[string]any, error) {",
        "\tstate := map[string]any{}",
        "",
    ]
    prev_var = "kwargs"
    for elem in graph.flow.chain:
        if not isinstance(elem, CallIR):
            continue  # control flow handled in T12-T15
        step = steps_by_name.get(elem.step_name)
        if step is None or step.mode != "exact":
            continue  # judgment steps in T11
        cls = _to_class_name(step.name)
        input_init = _kwargs_to_step_input(step, prev_var, contracts_by_name)
        out_var = f"{step.name}Out"
        lines.extend([
            f"\t{out_var}, err := steps.{cls}(ctx, {input_init})",
            "\tif err != nil {",
            "\t\treturn nil, err",
            "\t}",
            f'\tstate["{step.name}"] = {out_var}',
            "",
        ])
        prev_var = out_var
    lines.append("\treturn state, nil")
    lines.append("}")
    return "\n".join(lines) + "\n"
