"""Helpers for the mcp-server emitter. Module-level functions only — emitters
import from here, never from each other."""
from __future__ import annotations

import json as _json

from clio.emitters._shared_utils import (
    _has_parallel,
    _python_condition_expr,
    _render_system_prompt,
    _to_field_name,
)
from clio.ir.contracts import type_to_json_schema
from clio.ir.graph import (
    CallIR,
    ErrorAccessIR,
    FlowCallIR,
    FlowGraph,
    FlowIR,
    ForEachIR,
    IfBlockIR,
    MatchBlockIR,
    RescueBlockIR,
    ResumeIR,
    StepIR,
    WhileBlockIR,
)
from clio.parser.ast_nodes import ContractRef, ListType


def _emit_readme(pkg_name: str, graph: FlowGraph) -> str:
    flow_name = graph.flow.name if graph.flow is not None else pkg_name
    return (
        f"# {pkg_name} — CLIO MCP server\n"
        "\n"
        "Auto-generated by `clio compile --target mcp-server`.\n"
        "\n"
        "## Install\n"
        "\n"
        "```bash\n"
        "pip install -e .\n"
        "```\n"
        "\n"
        "This pulls `mcp>=1.0` (and `pydantic`/`requests` if your flow needs them).\n"
        "\n"
        "## Add to your MCP client\n"
        "\n"
        "For Claude Desktop, edit `~/Library/Application Support/Claude/claude_desktop_config.json` "
        "(macOS) or the equivalent on your platform:\n"
        "\n"
        "```json\n"
        "{\n"
        '  "mcpServers": {\n'
        f'    "{pkg_name}": {{\n'
        '      "command": "python",\n'
        f'      "args": ["-m", "{pkg_name}"]\n'
        '    }\n'
        '  }\n'
        "}\n"
        "```\n"
        "\n"
        f"Restart your client. The tool will appear as `{flow_name}`.\n"
        "\n"
        "## How it works\n"
        "\n"
        "Each `FLOW` declared in the source `.clio` is exposed as an MCP tool. Judgment "
        "steps delegate to your client's LLM via `sampling/createMessage` — no API key on "
        "the server side.\n"
    )


def _pyproject_for_mcp(pkg_name: str, *, needs_pydantic: bool, needs_requests: bool) -> str:
    deps: list[str] = ['    "mcp>=1.0",']
    if needs_pydantic:
        deps.append('    "pydantic>=2",')
    if needs_requests:
        deps.append('    "requests>=2.31",')
    deps_block = "\n".join(deps)
    return (
        "[build-system]\n"
        'requires = ["setuptools>=70"]\n'
        'build-backend = "setuptools.build_meta"\n'
        "\n"
        "[project]\n"
        f'name = "{pkg_name}"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.12"\n'
        "dependencies = [\n"
        f"{deps_block}\n"
        "]\n"
        "\n"
        "[project.scripts]\n"
        f'{pkg_name} = "{pkg_name}.__main__:main"\n'
        "\n"
        "[tool.setuptools.packages.find]\n"
        f'include = ["{pkg_name}*"]\n'
    )


def _emit_main_module(pkg_name: str) -> str:
    return (
        '"""Stdio entry point for the mcp-server target."""\n'
        "from __future__ import annotations\n"
        "\n"
        "import asyncio\n"
        "\n"
        "from .server import server\n"
        "\n"
        "\n"
        "async def _run() -> None:\n"
        "    from mcp.server.stdio import stdio_server\n"
        "    async with stdio_server() as (read_stream, write_stream):\n"
        "        await server.run(\n"
        "            read_stream,\n"
        "            write_stream,\n"
        "            server.create_initialization_options(),\n"
        "        )\n"
        "\n"
        "\n"
        "def main() -> None:\n"
        "    asyncio.run(_run())\n"
        "\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )


def _first_step_of_flow(graph: FlowGraph, flow: FlowIR | None = None) -> StepIR | None:
    """Returns the StepIR for the first CallIR in `flow`'s chain (defaults to
    `graph.flow`), or None."""
    target = flow if flow is not None else graph.flow
    if target is None:
        return None
    by_name = {s.name: s for s in graph.steps}
    for elem in target.chain:
        if isinstance(elem, CallIR):
            return by_name.get(elem.step_name)
        if isinstance(elem, ForEachIR):
            for inner in elem.body:
                if isinstance(inner, CallIR):
                    return by_name.get(inner.step_name)
    return None


def _last_step_of_flow(graph: FlowGraph, flow: FlowIR | None = None) -> StepIR | None:
    """Returns the StepIR for the last CallIR in `flow`'s chain (defaults to
    `graph.flow`), or None."""
    target = flow if flow is not None else graph.flow
    if target is None:
        return None
    by_name = {s.name: s for s in graph.steps}
    last_call: CallIR | None = None

    def _walk(chain) -> None:
        nonlocal last_call
        for elem in chain:
            if isinstance(elem, CallIR):
                last_call = elem
            elif isinstance(elem, ForEachIR):
                _walk(elem.body)

    _walk(target.chain)
    return by_name.get(last_call.step_name) if last_call else None


def _declared_field_schema(t, contracts_by_name: dict) -> dict | None:
    """Render a JSON Schema for a declared FLOW.TAKES / FLOW.GIVES field type.

    Inlines `ContractRef` and `List<ContractRef>` because MCP clients cannot
    resolve `$ref` against an external definitions block. Falls back to
    `type_to_json_schema(t)` for primitives and inline records."""
    if isinstance(t, ContractRef):
        contract = contracts_by_name.get(t.name)
        return contract.json_schema if contract is not None else type_to_json_schema(t)
    if isinstance(t, ListType) and isinstance(t.inner, ContractRef):
        contract = contracts_by_name.get(t.inner.name)
        if contract is not None:
            return {"type": "array", "items": contract.json_schema}
    try:
        return type_to_json_schema(t)
    except (NotImplementedError, Exception):
        return None


def _output_schema_for_flow(graph: FlowGraph, flow: FlowIR | None = None) -> dict | None:
    target = flow if flow is not None else graph.flow
    # v0.16: prefer declared FLOW.GIVES when present.
    if target is not None and target.gives:
        contracts_by_name = {c.name: c for c in graph.contracts}

        if len(target.gives) == 1:
            return _declared_field_schema(target.gives[0].type, contracts_by_name)

        # Multi-field GIVES: wrap in an object schema.
        properties = {}
        required = []
        for f in target.gives:
            schema = _declared_field_schema(f.type, contracts_by_name)
            if schema is not None:
                properties[f.name] = schema
                required.append(f.name)
        return {"type": "object", "properties": properties, "required": required}

    # v0.15 fallback: infer from the last step's GIVES.
    last = _last_step_of_flow(graph, target)
    if last is None or last.gives is None:
        return None
    t = last.gives.type
    # ContractRef → expand the contract's JSON schema inline
    if isinstance(t, ContractRef):
        by_name = {c.name: c for c in graph.contracts}
        contract = by_name.get(t.name)
        if contract is None:
            return None
        return contract.json_schema
    # List<ContractRef> → inline items schema; never emit a $ref (clients can't resolve it)
    if isinstance(t, ListType) and isinstance(t.inner, ContractRef):
        by_name = {c.name: c for c in graph.contracts}
        contract = by_name.get(t.inner.name)
        if contract is None:
            return None
        return {"type": "array", "items": contract.json_schema}
    try:
        return type_to_json_schema(t)
    except (NotImplementedError, Exception):
        return None


def _input_schema_for_flow(graph: FlowGraph, flow: FlowIR | None = None) -> dict:
    target = flow if flow is not None else graph.flow
    # v0.16: prefer declared FLOW.TAKES when present. Uses the same
    # ContractRef-inlining helper as the output schema for symmetry.
    if target is not None and target.takes:
        contracts_by_name = {c.name: c for c in graph.contracts}
        properties = {}
        required = []
        for f in target.takes:
            schema = _declared_field_schema(f.type, contracts_by_name)
            if schema is not None:
                properties[f.name] = schema
                required.append(f.name)
        return {"type": "object", "properties": properties, "required": required}

    # v0.15 fallback: infer from the first step's TAKES, with literal-kwarg defaults.
    first = _first_step_of_flow(graph, target)
    if first is None or not first.takes:
        return {"type": "object", "properties": {}, "required": []}

    literal_defaults: dict[str, object] = {}
    if target is not None:
        for elem in target.chain:
            if isinstance(elem, CallIR) and elem.step_name == first.name:
                for kw_name, kw_val in elem.kwargs:
                    if not (isinstance(kw_val, str) and kw_val.startswith("@")):
                        literal_defaults[kw_name] = kw_val
                break

    properties = {}
    required = []
    for t in first.takes:
        prop = type_to_json_schema(t.type)
        if t.name in literal_defaults:
            prop["default"] = literal_defaults[t.name]
        else:
            required.append(t.name)
        properties[t.name] = prop
    return {"type": "object", "properties": properties, "required": required}


def _emit_server_module(pkg_name: str, graph: FlowGraph) -> str:
    flow_name = graph.flow.name if graph.flow is not None else None
    if flow_name is None:
        return (
            '"""MCP server for this CLIO-compiled package."""\n'
            "from __future__ import annotations\n"
            "\n"
            "from mcp.server.lowlevel import Server\n"
            "from mcp.types import TextContent, Tool\n"
            "\n"
            f"server = Server({pkg_name!r})\n"
            "\n"
            "\n"
            "@server.list_tools()\n"
            "async def list_tools() -> list[Tool]:\n"
            "    return []\n"
            "\n"
            "\n"
            "@server.call_tool()\n"
            "async def call_tool(name: str, arguments: dict) -> list[TextContent]:\n"
            "    raise ValueError(f'unknown tool: {name}')\n"
        )

    schema = _input_schema_for_flow(graph)
    output_schema = _output_schema_for_flow(graph)
    output_field = f"            outputSchema={output_schema!r},\n" if output_schema else ""
    tool_entry = (
        f"        Tool(\n"
        f"            name={flow_name!r},\n"
        f'            description="Auto-generated from FLOW {flow_name}",\n'
        f"            inputSchema={schema!r},\n"
        f"{output_field}"
        f"        )"
    )
    return (
        '"""MCP server for this CLIO-compiled package."""\n'
        "from __future__ import annotations\n"
        "\n"
        "import json\n"
        "\n"
        "from mcp.server.lowlevel import Server\n"
        "from mcp.types import TextContent, Tool\n"
        "\n"
        "from . import flow as _flow\n"
        "\n"
        f"server = Server({pkg_name!r})\n"
        "\n"
        "\n"
        "@server.list_tools()\n"
        "async def list_tools() -> list[Tool]:\n"
        "    return [\n"
        f"{tool_entry},\n"
        "    ]\n"
        "\n"
        "\n"
        "@server.call_tool()\n"
        "async def call_tool(name: str, arguments: dict) -> list[TextContent]:\n"
        "    ctx = server.request_context\n"
        f"    if name == {flow_name!r}:\n"
        "        result = await _flow.run(_session=ctx.session, **arguments)\n"
        '        return [TextContent(type="text", text=json.dumps(result, default=str))]\n'
        "    raise ValueError(f'unknown tool: {name}')\n"
    )


def _emit_flow_module_async(graph: FlowGraph) -> str:
    """Emit flow.py: an async run() that chains steps in flow order."""
    if graph.flow is None:
        return (
            '"""Async FLOW orchestrator. Auto-generated; do not edit."""\n'
            "from __future__ import annotations\n"
            "\n"
            "\n"
            "async def run(*, _session=None, **initial: object) -> dict:\n"
            "    return dict(initial)\n"
        )

    chain_lines: list[str] = []
    imported_steps: list[str] = []
    steps_by_name = {s.name: s for s in graph.steps}
    # RESCUE bookkeeping: names of steps protected by a RESCUE block (used to
    # wrap their call site in try/except) and the blocks themselves (used to
    # emit the async _rescue_<name> helper functions). Mirror of the python
    # target's pattern in clio/emitters/python.py:413.
    rescue_target_names = {rb.step_name for rb in graph.flow.rescues}
    rescues_by_step = {rb.step_name: rb for rb in graph.flow.rescues}

    def _emit_call(call: CallIR, indent: str, scope_local: set[str]) -> None:
        step = steps_by_name[call.step_name]
        if step.name not in imported_steps:
            imported_steps.append(step.name)
        kw_parts = []
        for name, value in call.kwargs:
            py_name = _to_field_name(name)
            if isinstance(value, ErrorAccessIR):
                if value.field == "message":
                    kw_parts.append(f"{py_name}=str(_err)")
                elif value.field == "type":
                    kw_parts.append(f"{py_name}=type(_err).__name__")
                else:
                    raise AssertionError(
                        f"unreachable: ErrorAccessIR field {value.field!r}"
                    )
            elif isinstance(value, str) and value.startswith("@"):
                ref = value[1:]
                if ref in scope_local:
                    kw_parts.append(f"{py_name}={_to_field_name(ref)}")
                else:
                    kw_parts.append(f"{py_name}=state[{ref!r}]")
            else:
                kw_parts.append(f"{py_name}={value!r}")
        kwargs_str = ", ".join(kw_parts)
        out_name = step.gives.name if step.gives is not None else "_result"
        is_judgment = step.mode == "judgment"
        if is_judgment:
            if kwargs_str:
                call_expr = f"{step.name}_mod.{step.name}({kwargs_str}, _session=_session)"
            else:
                call_expr = f"{step.name}_mod.{step.name}(_session=_session)"
            call_expr = f"await {call_expr}"
        else:
            call_expr = f"{step.name}_mod.{step.name}({kwargs_str})"
        if scope_local:
            call_line = call_expr
        else:
            call_line = f"state[{out_name!r}] = {call_expr}"
        # RESCUE: wrap the protected step's call site in try/except. Any
        # uncaught Exception triggers `await _rescue_<name>(state,
        # _session=_session)`; FlowAborted (raised by the rescue body's
        # terminal abort) propagates verbatim. The IR builder restricts
        # RESCUE targets to the top-level FLOW chain in v0.8, so this branch
        # is only reached when scope_local is empty — i.e. never inside a
        # FOR EACH / IF / MATCH / WHILE body. We still gate on
        # `not scope_local` for defence in depth (matches python.py:450).
        if step.name in rescue_target_names and not scope_local:
            rb = rescues_by_step[step.name]
            terminator = rb.body[-1]
            chain_lines.append(f"{indent}try:")
            chain_lines.append(f"{indent}    {call_line}")
            chain_lines.append(f"{indent}except FlowAborted:")
            chain_lines.append(f"{indent}    raise")
            chain_lines.append(f"{indent}except Exception as _err:")
            if isinstance(terminator, ResumeIR):
                assert step.gives is not None  # T9 validates: RESUME requires GIVES
                rescued_gives_field = step.gives.name
                chain_lines.append(
                    f"{indent}    state[{rescued_gives_field!r}] = "
                    f"await _rescue_{step.name}(state, _err, _session=_session)"
                )
            else:
                chain_lines.append(
                    f"{indent}    await _rescue_{step.name}(state, _err, _session=_session)"
                )
                chain_lines.append(f"{indent}    raise")
        else:
            chain_lines.append(f"{indent}{call_line}")

    def _emit_item(item, indent: str, scope_local: set[str]) -> None:
        # `abort("msg")` is a synthetic CallIR injected by the IR builder
        # only inside RESCUE bodies. It compiles to `raise FlowAborted(msg)`
        # regardless of context (rescue body root, or nested IF/MATCH/
        # WHILE/FOR EACH inside the rescue body). Placed at the top of
        # _emit_item so every recursive call site picks it up. Mirror of
        # python.py:467.
        if isinstance(item, CallIR) and item.step_name == "abort":
            msg = next(
                (v for k, v in item.kwargs if k == "message"), ""
            )
            chain_lines.append(f"{indent}raise FlowAborted({msg!r})")
            return
        if isinstance(item, ForEachIR):
            if item.parallel:
                chain_lines.append(emit_parallel_for_each_mcp(item, steps_by_name, indent))
                inner = item.body[0]
                # v0.17: sub-flow body needs no step import (the sub-flow
                # function is emitted in the same module). Only track step
                # imports for CallIR bodies.
                if isinstance(inner, CallIR):
                    if inner.step_name not in imported_steps:
                        imported_steps.append(inner.step_name)
                return
            source = (
                item.collection
                if item.collection in scope_local
                else f"state[{item.collection!r}]"
            )
            chain_lines.append(f"{indent}for {_to_field_name(item.loop_var)} in {source}:")
            inner_scope = scope_local | {item.loop_var}
            inner_indent = indent + "    "
            if not item.body:
                chain_lines.append(f"{inner_indent}pass")
            for sub in item.body:
                _emit_item(sub, inner_indent, inner_scope)
            return
        if isinstance(item, IfBlockIR):
            cond_expr = _python_condition_expr(item.condition, scope_local)
            chain_lines.append(f"{indent}if {cond_expr}:")
            inner_indent = indent + "    "
            if not item.then_body:
                chain_lines.append(f"{inner_indent}pass")
            for sub in item.then_body:
                _emit_item(sub, inner_indent, scope_local)
            if item.else_body:
                chain_lines.append(f"{indent}else:")
                for sub in item.else_body:
                    _emit_item(sub, inner_indent, scope_local)
            return
        if isinstance(item, MatchBlockIR):
            base = (
                item.state_field
                if item.state_field in scope_local
                else f"state[{item.state_field!r}]"
            )
            chain_lines.append(f"{indent}match {base}.{item.sub_field}:")
            inner_indent = indent + "    "
            for arm in item.cases:
                if arm.value is None:
                    chain_lines.append(f"{inner_indent}case _:")
                else:
                    chain_lines.append(f"{inner_indent}case {arm.value!r}:")
                body_indent = inner_indent + "    "
                if not arm.body:
                    chain_lines.append(f"{body_indent}pass")
                for sub in arm.body:
                    _emit_item(sub, body_indent, scope_local)
            return
        if isinstance(item, WhileBlockIR):
            cond_expr = _python_condition_expr(item.condition, scope_local)
            chain_lines.append(f"{indent}for _i in range({item.max_iters}):")
            inner_indent = indent + "    "
            chain_lines.append(f"{inner_indent}if not ({cond_expr}):")
            chain_lines.append(f"{inner_indent}    break")
            if not item.body:
                chain_lines.append(f"{inner_indent}pass")
            for sub in item.body:
                _emit_item(sub, inner_indent, scope_local)
            return
        if isinstance(item, ResumeIR):
            chain_lines.append(f"{indent}return state[{item.field_name!r}]")
            return
        if isinstance(item, CallIR):
            _emit_call(item, indent, scope_local)
            return
        raise ValueError(f"unknown flow item: {type(item).__name__}")

    for item in graph.flow.chain:
        _emit_item(item, "    ", set())

    # Snapshot the main chain lines before re-using the walker for rescue
    # bodies (the closure mutates the shared `chain_lines` list).
    main_chain_lines = list(chain_lines)

    # Emit one async _rescue_<step_name>(state, _session=None) helper per
    # RESCUE block. Each helper body is rendered with the same _emit_item
    # walker; the body's terminal abort(...) is rewritten to `raise
    # FlowAborted(msg)`, so the helper never returns normally. The helpers
    # live at module level (after `run`) and are called from the wrapped
    # try/except in the main chain. _session is threaded through so
    # judgment-mode steps inside the rescue body inherit it (mirrors the
    # FOR EACH PARALLEL pattern at emit_parallel_for_each_mcp).
    rescue_helpers: list[str] = []
    for rb in graph.flow.rescues:
        chain_lines.clear()
        for sub in rb.body:
            _emit_item(sub, "    ", set())
        rescue_body = "\n".join(chain_lines)
        terminator = rb.body[-1]
        ret_ann = "object" if isinstance(terminator, ResumeIR) else "None"
        rescue_helpers.append(
            f"async def _rescue_{rb.step_name}(state: dict, _err: BaseException, _session=None) -> {ret_ann}:\n"
            + rescue_body
            + "\n"
        )

    imports = "\n".join(f"from .steps import {n} as {n}_mod" for n in imported_steps)
    asyncio_import = "import asyncio\n\n" if _has_parallel(graph.flow.chain) else ""

    # main_chain_lines start with "    " (4 spaces) for top-level items; some
    # entries are multi-line strings (parallel FOR EACH). We re-indent every
    # line of every entry by 4 more spaces so the chain runs inside `try:`.
    chain_body = "\n".join(
        "\n".join("    " + line for line in cl.split("\n"))
        for cl in main_chain_lines
    )
    # FlowAborted is defined locally in the emitted flow module when at least
    # one RESCUE block is present. Keeping the class here (rather than in
    # clio_runtime) means flow.py is self-contained for rescue semantics and
    # existing snapshot fixtures stay byte-identical when no RESCUE is
    # declared. Mirror of python.py:590.
    flow_aborted_block = (
        "class FlowAborted(Exception):\n"
        "    \"\"\"Raised by RESCUE bodies' terminal abort(...) call. Propagates out\n"
        "    of `run()` and is re-raised verbatim by any try/except wrapper around\n"
        "    a protected step's call site.\"\"\"\n"
        "    pass\n"
        "\n"
        "\n"
        if graph.flow.rescues else ""
    )
    rescue_helpers_block = (
        "\n\n" + "\n\n".join(rescue_helpers) if rescue_helpers else ""
    )
    flow_name_lit = _json.dumps(graph.flow.name)
    return (
        '"""Async FLOW orchestrator. Auto-generated; do not edit."""\n'
        "from __future__ import annotations\n"
        "\n"
        "import time\n"
        f"{asyncio_import}"
        f"{imports}\n"
        "\n"
        "from .clio_runtime import logging as _log\n"
        "\n"
        "\n"
        f"{flow_aborted_block}"
        "async def run(*, _session=None, **initial: object) -> dict:\n"
        "    state: dict = dict(initial)\n"
        f"    _log.set_flow({flow_name_lit})\n"
        '    _log.emit("flow_start")\n'
        "    _success = False\n"
        "    _t0 = time.monotonic()\n"
        "    try:\n"
        f"{chain_body}\n"
        "        _success = True\n"
        "        return state\n"
        "    finally:\n"
        '        _log.emit("flow_end", '
        "duration_ms=int((time.monotonic() - _t0) * 1000), "
        "success=_success)\n"
        "        _log.set_flow(None)\n"
        f"{rescue_helpers_block}"
    )


def _emit_server_module_multi(pkg_name: str, graph: FlowGraph) -> str:
    """v0.17 multi-FLOW server: one Tool entry per exposed FLOW, dispatched by
    name. Each tool delegates to the corresponding async function in flow.py."""
    exposed = sorted(graph.exposed_flow_names)
    flows_by_name = {f.name: f for f in graph.flows}

    tool_entries: list[str] = []
    dispatch_lines: list[str] = []
    for flow_name in exposed:
        flow = flows_by_name[flow_name]
        schema = _input_schema_for_flow(graph, flow)
        output_schema = _output_schema_for_flow(graph, flow)
        output_field = (
            f"            outputSchema={output_schema!r},\n" if output_schema else ""
        )
        tool_entries.append(
            f"        Tool(\n"
            f"            name={flow_name!r},\n"
            f'            description="Auto-generated from FLOW {flow_name}",\n'
            f"            inputSchema={schema!r},\n"
            f"{output_field}"
            f"        )"
        )
        # Sanitize the Python attribute access (the function name in flow.py);
        # the MCP `name == ...` string still matches the user-declared FLOW name.
        py_flow_name = _to_field_name(flow_name)
        dispatch_lines.append(
            f"    if name == {flow_name!r}:\n"
            f"        result = await _flow.{py_flow_name}(_session=ctx.session, **arguments)\n"
            f'        return [TextContent(type="text", text=json.dumps(result, default=str))]'
        )

    if not tool_entries:
        # Every FLOW is called by a sibling — no tools exposed. Emit an empty
        # server rather than failing, matching the v0.16 "no flow" stub.
        return (
            '"""MCP server for this CLIO-compiled package."""\n'
            "from __future__ import annotations\n"
            "\n"
            "from mcp.server.lowlevel import Server\n"
            "from mcp.types import TextContent, Tool\n"
            "\n"
            f"server = Server({pkg_name!r})\n"
            "\n"
            "\n"
            "@server.list_tools()\n"
            "async def list_tools() -> list[Tool]:\n"
            "    return []\n"
            "\n"
            "\n"
            "@server.call_tool()\n"
            "async def call_tool(name: str, arguments: dict) -> list[TextContent]:\n"
            "    raise ValueError(f'unknown tool: {name}')\n"
        )

    tools_block = ",\n".join(tool_entries) + ",\n"
    dispatch_block = "\n".join(dispatch_lines)
    return (
        '"""MCP server for this CLIO-compiled package."""\n'
        "from __future__ import annotations\n"
        "\n"
        "import json\n"
        "\n"
        "from mcp.server.lowlevel import Server\n"
        "from mcp.types import TextContent, Tool\n"
        "\n"
        "from . import flow as _flow\n"
        "\n"
        f"server = Server({pkg_name!r})\n"
        "\n"
        "\n"
        "@server.list_tools()\n"
        "async def list_tools() -> list[Tool]:\n"
        "    return [\n"
        f"{tools_block}"
        "    ]\n"
        "\n"
        "\n"
        "@server.call_tool()\n"
        "async def call_tool(name: str, arguments: dict) -> list[TextContent]:\n"
        "    ctx = server.request_context\n"
        f"{dispatch_block}\n"
        "    raise ValueError(f'unknown tool: {name}')\n"
    )


def _emit_flow_module_async_multi(graph: FlowGraph) -> str:
    """v0.17 multi-FLOW flow.py: one async function per FLOW in `graph.flows`.

    Each function chains its own steps, handles its own RESCUE blocks, and
    returns either its declared GIVES (when signed) or the full state. Sub-flow
    calls compile to `state.update(await <name>(...))` — same flat-GIVES
    convention as the python target's `state.update(run_<name>(...))`."""
    steps_by_name = {s.name: s for s in graph.steps}
    imported_steps: list[str] = []
    chain_lines: list[str] = []
    has_any_rescue = any(f.rescues for f in graph.flows)

    # Per-flow rescue context (rebuilt before each flow's chain pass and each
    # rescue body pass).
    rescue_target_names: set[str] = set()
    rescues_by_step: dict[str, RescueBlockIR] = {}

    def _set_flow_ctx(flow: FlowIR) -> None:
        rescue_target_names.clear()
        rescue_target_names.update(rb.step_name for rb in flow.rescues)
        rescues_by_step.clear()
        rescues_by_step.update({rb.step_name: rb for rb in flow.rescues})

    def _emit_call(call: CallIR, indent: str, scope_local: set[str]) -> None:
        step = steps_by_name[call.step_name]
        if step.name not in imported_steps:
            imported_steps.append(step.name)
        kw_parts = []
        for name, value in call.kwargs:
            py_name = _to_field_name(name)
            if isinstance(value, ErrorAccessIR):
                if value.field == "message":
                    kw_parts.append(f"{py_name}=str(_err)")
                elif value.field == "type":
                    kw_parts.append(f"{py_name}=type(_err).__name__")
                else:
                    raise AssertionError(
                        f"unreachable: ErrorAccessIR field {value.field!r}"
                    )
            elif isinstance(value, str) and value.startswith("@"):
                ref = value[1:]
                if ref in scope_local:
                    kw_parts.append(f"{py_name}={_to_field_name(ref)}")
                else:
                    kw_parts.append(f"{py_name}=state[{ref!r}]")
            else:
                kw_parts.append(f"{py_name}={value!r}")
        kwargs_str = ", ".join(kw_parts)
        out_name = step.gives.name if step.gives is not None else "_result"
        is_judgment = step.mode == "judgment"
        if is_judgment:
            if kwargs_str:
                call_expr = f"{step.name}_mod.{step.name}({kwargs_str}, _session=_session)"
            else:
                call_expr = f"{step.name}_mod.{step.name}(_session=_session)"
            call_expr = f"await {call_expr}"
        else:
            call_expr = f"{step.name}_mod.{step.name}({kwargs_str})"
        if scope_local:
            call_line = call_expr
        else:
            call_line = f"state[{out_name!r}] = {call_expr}"
        if step.name in rescue_target_names and not scope_local:
            rb = rescues_by_step[step.name]
            terminator = rb.body[-1]
            chain_lines.append(f"{indent}try:")
            chain_lines.append(f"{indent}    {call_line}")
            chain_lines.append(f"{indent}except FlowAborted:")
            chain_lines.append(f"{indent}    raise")
            chain_lines.append(f"{indent}except Exception as _err:")
            if isinstance(terminator, ResumeIR):
                assert step.gives is not None
                rescued_gives_field = step.gives.name
                chain_lines.append(
                    f"{indent}    state[{rescued_gives_field!r}] = "
                    f"await _rescue_{step.name}(state, _err, _session=_session)"
                )
            else:
                chain_lines.append(
                    f"{indent}    await _rescue_{step.name}(state, _err, _session=_session)"
                )
                chain_lines.append(f"{indent}    raise")
        else:
            chain_lines.append(f"{indent}{call_line}")

    def _emit_flow_call(call: FlowCallIR, indent: str, scope_local: set[str]) -> None:
        kw_parts = []
        for name, value in call.kwargs:
            py_name = _to_field_name(name)
            if isinstance(value, str) and value.startswith("@"):
                ref = value[1:]
                if ref in scope_local:
                    kw_parts.append(f"{py_name}={_to_field_name(ref)}")
                else:
                    kw_parts.append(f"{py_name}=state[{ref!r}]")
            else:
                kw_parts.append(f"{py_name}={value!r}")
        kwargs_str = ", ".join(kw_parts)
        sep = ", " if kwargs_str else ""
        invocation = (
            f"await {_to_field_name(call.flow_name)}"
            f"(_session=_session{sep}{kwargs_str})"
        )
        if scope_local:
            chain_lines.append(f"{indent}{invocation}")
        else:
            chain_lines.append(f"{indent}state.update({invocation})")

    def _emit_item(item, indent: str, scope_local: set[str]) -> None:
        if isinstance(item, CallIR) and item.step_name == "abort":
            msg = next((v for k, v in item.kwargs if k == "message"), "")
            chain_lines.append(f"{indent}raise FlowAborted({msg!r})")
            return
        if isinstance(item, ForEachIR):
            if item.parallel:
                chain_lines.append(emit_parallel_for_each_mcp(item, steps_by_name, indent))
                inner = item.body[0]
                # v0.17: sub-flow body needs no step import.
                if isinstance(inner, CallIR):
                    if inner.step_name not in imported_steps:
                        imported_steps.append(inner.step_name)
                return
            source = (
                item.collection
                if item.collection in scope_local
                else f"state[{item.collection!r}]"
            )
            chain_lines.append(f"{indent}for {_to_field_name(item.loop_var)} in {source}:")
            inner_scope = scope_local | {item.loop_var}
            inner_indent = indent + "    "
            if not item.body:
                chain_lines.append(f"{inner_indent}pass")
            for sub in item.body:
                _emit_item(sub, inner_indent, inner_scope)
            return
        if isinstance(item, IfBlockIR):
            cond_expr = _python_condition_expr(item.condition, scope_local)
            chain_lines.append(f"{indent}if {cond_expr}:")
            inner_indent = indent + "    "
            if not item.then_body:
                chain_lines.append(f"{inner_indent}pass")
            for sub in item.then_body:
                _emit_item(sub, inner_indent, scope_local)
            if item.else_body:
                chain_lines.append(f"{indent}else:")
                for sub in item.else_body:
                    _emit_item(sub, inner_indent, scope_local)
            return
        if isinstance(item, MatchBlockIR):
            base = (
                item.state_field
                if item.state_field in scope_local
                else f"state[{item.state_field!r}]"
            )
            chain_lines.append(f"{indent}match {base}.{item.sub_field}:")
            inner_indent = indent + "    "
            for arm in item.cases:
                if arm.value is None:
                    chain_lines.append(f"{inner_indent}case _:")
                else:
                    chain_lines.append(f"{inner_indent}case {arm.value!r}:")
                body_indent = inner_indent + "    "
                if not arm.body:
                    chain_lines.append(f"{body_indent}pass")
                for sub in arm.body:
                    _emit_item(sub, body_indent, scope_local)
            return
        if isinstance(item, WhileBlockIR):
            cond_expr = _python_condition_expr(item.condition, scope_local)
            chain_lines.append(f"{indent}for _i in range({item.max_iters}):")
            inner_indent = indent + "    "
            chain_lines.append(f"{inner_indent}if not ({cond_expr}):")
            chain_lines.append(f"{inner_indent}    break")
            if not item.body:
                chain_lines.append(f"{inner_indent}pass")
            for sub in item.body:
                _emit_item(sub, inner_indent, scope_local)
            return
        if isinstance(item, ResumeIR):
            chain_lines.append(f"{indent}return state[{item.field_name!r}]")
            return
        if isinstance(item, FlowCallIR):
            _emit_flow_call(item, indent, scope_local)
            return
        if isinstance(item, CallIR):
            _emit_call(item, indent, scope_local)
            return
        raise ValueError(f"unknown flow item: {type(item).__name__}")

    # Render one async def per FLOW. Iterate `graph.flows` (alphabetical via
    # the IR's declaration order — stable across runs of the same source).
    flow_funcs: list[str] = []
    has_parallel = any(_has_parallel(f.chain) for f in graph.flows)
    for flow in graph.flows:
        _set_flow_ctx(flow)
        chain_lines.clear()
        for item in flow.chain:
            _emit_item(item, "        ", set())
        body_lines = list(chain_lines)

        # Rescue helpers for this flow. Names are scoped per-flow but we keep
        # the existing `_rescue_<step_name>` convention; since IR-level
        # validation forbids duplicate step names across STEPs, and RESCUE
        # bindings are step-by-name, helpers don't collide. Still, multiple
        # flows can rescue the same step — emit one helper per RESCUE
        # declaration via a flow-suffixed name.
        rescue_helpers_for_flow: list[str] = []
        for rb in flow.rescues:
            chain_lines.clear()
            for sub in rb.body:
                _emit_item(sub, "    ", set())
            rescue_body = "\n".join(chain_lines)
            terminator = rb.body[-1]
            ret_ann = "object" if isinstance(terminator, ResumeIR) else "None"
            rescue_helpers_for_flow.append(
                f"async def _rescue_{rb.step_name}(state: dict, _err: BaseException, _session=None) -> {ret_ann}:\n"
                + rescue_body
                + "\n"
            )

        flow_name_lit = _json.dumps(flow.name)
        py_flow_name = _to_field_name(flow.name)
        # Initialize state and emit chain.
        body = (
            f"async def {py_flow_name}(*, _session=None, **initial: object) -> dict:\n"
            "    state: dict = dict(initial)\n"
            f"    _log.set_flow({flow_name_lit})\n"
            '    _log.emit("flow_start")\n'
            "    _success = False\n"
            "    _t0 = time.monotonic()\n"
            "    try:\n"
        )
        if body_lines:
            body += "\n".join(body_lines) + "\n"
        else:
            body += "        pass\n"
        body += "        _success = True\n"
        if flow.gives:
            return_expr = (
                "        return {"
                + ", ".join(f"{f.name!r}: state[{f.name!r}]" for f in flow.gives)
                + "}\n"
            )
        else:
            return_expr = "        return state\n"
        body += return_expr
        body += (
            "    finally:\n"
            '        _log.emit("flow_end", '
            "duration_ms=int((time.monotonic() - _t0) * 1000), "
            "success=_success)\n"
            "        _log.set_flow(None)\n"
        )
        if rescue_helpers_for_flow:
            body += "\n\n" + "\n\n".join(rescue_helpers_for_flow)
        flow_funcs.append(body)

    imports = "\n".join(f"from .steps import {n} as {n}_mod" for n in imported_steps)
    asyncio_import = "import asyncio\n\n" if has_parallel else ""
    flow_aborted_block = (
        "class FlowAborted(Exception):\n"
        "    \"\"\"Raised by RESCUE bodies' terminal abort(...) call. Propagates out\n"
        "    of the enclosing flow function and is re-raised verbatim by any\n"
        "    try/except wrapper around a protected step's call site.\"\"\"\n"
        "    pass\n"
        "\n"
        "\n"
        if has_any_rescue else ""
    )

    return (
        '"""Async FLOW orchestrators (multi-FLOW). Auto-generated; do not edit."""\n'
        "from __future__ import annotations\n"
        "\n"
        "import time\n"
        f"{asyncio_import}"
        + (f"{imports}\n" if imports else "")
        + "\n"
        "from .clio_runtime import logging as _log\n"
        "\n"
        "\n"
        f"{flow_aborted_block}"
        + "\n\n".join(flow_funcs)
    )


def emit_parallel_for_each_mcp(
    elem: ForEachIR,
    steps_by_name: dict,
    indent: str,
) -> str:
    """Emit an asyncio.gather block for a parallel FOR EACH (mcp-server target).

    v0.17 — body is either a CallIR (step body) or a FlowCallIR (sub-flow body).
    For sub-flows the per-iteration call is `await <flow_name>(...)` and the
    collector receives `list[dict[str, ...]]` of the sub-flow's GIVES.
    """
    inner = elem.body[0]
    # IR validator enforces this — assert so mypy can narrow the Union.
    assert isinstance(inner, (CallIR, FlowCallIR))

    scope_local = {elem.loop_var}
    kw_parts: list[str] = []
    for name, value in inner.kwargs:
        py_name = _to_field_name(name)
        if isinstance(value, str) and value.startswith("@"):
            ref = value[1:]
            if ref in scope_local:
                kw_parts.append(f"{py_name}={_to_field_name(ref)}")
            else:
                kw_parts.append(f"{py_name}=state[{ref!r}]")
        else:
            kw_parts.append(f"{py_name}={value!r}")
    kwargs_str = ", ".join(kw_parts)

    if isinstance(inner, CallIR):
        step = steps_by_name[inner.step_name]
        is_judgment = step.mode == "judgment"
        if is_judgment:
            if kwargs_str:
                call_expr = f"await {step.name}_mod.{step.name}({kwargs_str}, _session=_session)"
            else:
                call_expr = f"await {step.name}_mod.{step.name}(_session=_session)"
        else:
            call_expr = f"{step.name}_mod.{step.name}({kwargs_str})"
        unit_kv = f"step={step.name!r}"
    elif isinstance(inner, FlowCallIR):
        sep = ", " if kwargs_str else ""
        call_expr = (
            f"await {_to_field_name(inner.flow_name)}"
            f"(_session=_session{sep}{kwargs_str})"
        )
        unit_kv = f"flow={inner.flow_name!r}"
    else:
        raise AssertionError(
            f"unreachable: PARALLEL FOR EACH body must be CallIR or "
            f"FlowCallIR, got {type(inner).__name__}"
        )

    items_lookup = f"state[{elem.collection!r}]"
    bound_name = f"_bound_{elem.collector}"

    return (
        f"{indent}_items = {items_lookup}\n"
        f"{indent}_sem = asyncio.Semaphore(10)\n"
        f"{indent}async def {bound_name}({_to_field_name(elem.loop_var)}):\n"
        f"{indent}    async with _sem:\n"
        f"{indent}        return {call_expr}\n"
        f'{indent}_log.emit("parallel_block_start", {unit_kv}, '
        f"collector={elem.collector!r}, total_iterations=len(_items), max_workers=10)\n"
        f"{indent}_pblock_t0 = time.monotonic()\n"
        f"{indent}_pblock_success = False\n"
        f"{indent}try:\n"
        f"{indent}    state[{elem.collector!r}] = await asyncio.gather("
        f"*[{bound_name}(_x) for _x in _items])\n"
        f"{indent}    _pblock_success = True\n"
        f"{indent}finally:\n"
        f'{indent}    _log.emit("parallel_block_end", {unit_kv}, '
        f"collector={elem.collector!r}, total_iterations=len(_items), "
        f"duration_ms=int((time.monotonic() - _pblock_t0) * 1000), success=_pblock_success)"
    )


def emit_judgment_step_via_sampling(
    step: StepIR, graph: FlowGraph, contracts_by_name: dict
) -> str:
    """Emit a judgment step that delegates to the MCP client via
    session.create_message(...). No anthropic/openai SDK in the emitted code."""
    from clio.emitters._claude_cli_helpers import _inline_schema, _render_prompt
    from clio.emitters._python_helpers import _step_signature, _to_class_name, _type_to_python
    from clio.parser.ast_nodes import ContractRef, ListType

    params = _step_signature(step, contracts_by_name)
    # Append _session keyword argument to the existing kwargs-only signature.
    if params:
        params_with_session = f"{params}, _session"
    else:
        params_with_session = "*, _session"

    ret_type = (
        _type_to_python(step.gives.type, contracts_by_name)
        if step.gives is not None else "None"
    )

    prompt_template = _render_prompt(step)

    # Bug fix #1: schema must be JSON string at emit time so str.replace works at runtime.
    # Bug fix #2: pass contracts_by_name (dict), not graph.contracts (tuple).
    if step.gives is not None:
        inlined = _inline_schema(step.gives.type, contracts_by_name)
        inlined_json = _json.dumps(inlined, separators=(",", ":"))
    else:
        inlined_json = "{}"

    sub_lines = [
        f"    prompt = prompt.replace('${{{t.name}}}', json.dumps({t.name}))"
        for t in step.takes
    ]
    sub_lines.append("    prompt = prompt.replace('${schema}', _INLINED_SCHEMA)")
    sub_block = "\n".join(sub_lines)

    if step.gives is None:
        validate_block = "    return None"
    else:
        t = step.gives.type
        if isinstance(t, ContractRef):
            cls = _to_class_name(t.name)
            validate_block = (
                f"    return contracts.{cls}.model_validate(json.loads(cleaned))"
            )
        elif isinstance(t, ListType) and isinstance(t.inner, ContractRef):
            cls = _to_class_name(t.inner.name)
            validate_block = (
                f"    return [contracts.{cls}.model_validate(item) "
                f"for item in json.loads(cleaned)]"
            )
        else:
            validate_block = "    return json.loads(cleaned)"

    has_contracts = bool(graph.contracts)
    contracts_import = "from .. import contracts\n" if has_contracts else ""

    # ON_FAIL: compute retry count from the first retry strategy (if any)
    strategies = step.on_fail.strategies if step.on_fail is not None else ()
    retry_max = 0
    for s in strategies:
        if s.kind == "retry":
            retry_max = s.max_retries or 1
            break
    has_on_fail = bool(strategies)

    # Strip the "return " prefix from validate_block to get the bare expression
    # for assignment to _ret. validate_block always begins with 4 spaces of
    # indent and the keyword "return ". Handles all 4 variants:
    #   "    return None"
    #   "    return json.loads(cleaned)"
    #   "    return contracts.X.model_validate(json.loads(cleaned))"
    #   "    return [contracts.X.model_validate(item) for item in json.loads(cleaned)]"
    validate_expr = validate_block.lstrip().removeprefix("return ")

    if has_on_fail:
        retry_max_line = f"_RETRY_MAX = {retry_max}\n"
        body_lines = (
            f"async def {step.name}({params_with_session}) -> {ret_type}:\n"
            "    _t0 = time.monotonic()\n"
            f'    _log.emit("step_start", step={step.name!r}, mode="judgment")\n'
            "    _last_model = None\n"
            "    _last_usage: dict = {}\n"
            "    prompt = _PROMPT_TEMPLATE\n"
            f"{sub_block}\n"
            "    last_exc = None\n"
            "    for _attempt_idx in range(_RETRY_MAX + 1):\n"
            "        try:\n"
            "            from mcp.types import SamplingMessage, TextContent\n"
            "            msg = await _session.create_message(\n"
            "                messages=[\n"
            "                    SamplingMessage(\n"
            "                        role='user',\n"
            "                        content=TextContent(type='text', text=prompt),\n"
            "                    )\n"
            "                ],\n"
            "                max_tokens=_MAX_TOKENS,\n"
            "                system_prompt=_SYSTEM_PROMPT,\n"
            "            )\n"
            "            if hasattr(msg, 'model') and msg.model:\n"
            "                _last_model = msg.model\n"
            "            if hasattr(msg, 'usage') and msg.usage is not None:\n"
            "                _last_usage = {\n"
            "                    'tokens_in': getattr(msg.usage, 'input_tokens', None),\n"
            "                    'tokens_out': getattr(msg.usage, 'output_tokens', None),\n"
            "                }\n"
            "                _last_usage = {k: v for k, v in _last_usage.items() if v is not None}\n"
            "            raw = msg.content.text if getattr(msg.content, 'type', None) == 'text' else ''\n"
            "            cleaned = '\\n'.join(line for line in raw.splitlines() if not line.startswith('```'))\n"
            f"            _ret = ({validate_expr})\n"
            f'            _log.emit("step_end", step={step.name!r}, mode="judgment",\n'
            "                      duration_ms=int((time.monotonic() - _t0) * 1000),\n"
            "                      cache_hit=False, model=_last_model,\n"
            "                      fallback_used=False, success=True, **_last_usage)\n"
            "            return _ret\n"
            "        except Exception as _e:\n"
            "            last_exc = _e\n"
            "    if last_exc is not None:\n"
            f'        _log.emit("step_end", step={step.name!r}, mode="judgment",\n'
            "                  duration_ms=int((time.monotonic() - _t0) * 1000),\n"
            "                  cache_hit=False, model=_last_model,\n"
            "                  fallback_used=False, success=False)\n"
            "        raise last_exc\n"
        )
    else:
        retry_max_line = ""
        # Re-indent sub_block by 4 extra spaces because it lives inside `try:`.
        sub_block_in_try = "\n".join(
            ("    " + line) if line else line for line in sub_block.split("\n")
        )
        body_lines = (
            f"async def {step.name}({params_with_session}) -> {ret_type}:\n"
            "    _t0 = time.monotonic()\n"
            f'    _log.emit("step_start", step={step.name!r}, mode="judgment")\n'
            "    _last_model = None\n"
            "    _last_usage: dict = {}\n"
            "    try:\n"
            "        prompt = _PROMPT_TEMPLATE\n"
            f"{sub_block_in_try}\n"
            "        from mcp.types import SamplingMessage, TextContent\n"
            "        msg = await _session.create_message(\n"
            "            messages=[\n"
            "                SamplingMessage(\n"
            "                    role='user',\n"
            "                    content=TextContent(type='text', text=prompt),\n"
            "                )\n"
            "            ],\n"
            "            max_tokens=_MAX_TOKENS,\n"
            "            system_prompt=_SYSTEM_PROMPT,\n"
            "        )\n"
            "        if hasattr(msg, 'model') and msg.model:\n"
            "            _last_model = msg.model\n"
            "        if hasattr(msg, 'usage') and msg.usage is not None:\n"
            "            _last_usage = {\n"
            "                'tokens_in': getattr(msg.usage, 'input_tokens', None),\n"
            "                'tokens_out': getattr(msg.usage, 'output_tokens', None),\n"
            "            }\n"
            "            _last_usage = {k: v for k, v in _last_usage.items() if v is not None}\n"
            "        raw = msg.content.text if getattr(msg.content, 'type', None) == 'text' else ''\n"
            "        cleaned = '\\n'.join(line for line in raw.splitlines() if not line.startswith('```'))\n"
            f"        _ret = ({validate_expr})\n"
            f'        _log.emit("step_end", step={step.name!r}, mode="judgment",\n'
            "                  duration_ms=int((time.monotonic() - _t0) * 1000),\n"
            "                  cache_hit=False, model=_last_model,\n"
            "                  fallback_used=False, success=True, **_last_usage)\n"
            "        return _ret\n"
            "    except Exception:\n"
            f'        _log.emit("step_end", step={step.name!r}, mode="judgment",\n'
            "                  duration_ms=int((time.monotonic() - _t0) * 1000),\n"
            "                  cache_hit=False, model=_last_model,\n"
            "                  fallback_used=False, success=False)\n"
            "        raise\n"
        )

    return (
        f'"""STEP {step.name} (judgment, mcp_sampling).\n'
        f'Auto-generated. Do not edit; regenerate via `clio compile`.\n'
        f'"""\n'
        "from __future__ import annotations\n"
        "\n"
        "import json\n"
        "import time\n"
        "\n"
        f"{contracts_import}"
        "from ..clio_runtime import logging as _log\n"
        "\n"
        f"_PROMPT_TEMPLATE = {prompt_template!r}\n"
        f"_INLINED_SCHEMA = {inlined_json!r}\n"
        f"{chr(10).join(_render_system_prompt(step))}\n"
        "_MAX_TOKENS = 4096\n"
        f"{retry_max_line}"
        "\n"
        "\n"
        f"{body_lines}"
    )
