"""Static Swift runtime templates emitted under Sources/ClioFlow/Runtime/.

These are pure Swift source strings: no per-graph substitution.
`render_runtime_validate_swift` returns the Validate.swift content verbatim.

Why a separate module: mirrors the pattern of _go_runtime_templates.py, keeping
_swift_helpers.py focused on graph-bound rendering.
"""
from __future__ import annotations

# NOTE: this is a Python raw string (r-prefix) so that Swift's \(interpolation)
# syntax passes through unmodified — Python does NOT process the backslash sequences.
_VALIDATE_SWIFT_TEMPLATE = r"""// Auto-generated by CLIO. Do not edit by hand.
// Zero-dependency structural validator for CLIO contract schemas.
// Mirrors clio/runtime/validate.py and clio/emitters/_go_runtime_templates.py
// but uses only Foundation (JSONEncoder + JSONSerialization) — no external deps.
import Foundation

// MARK: - ValidationError

struct ValidationError: Error {
    let message: String
    var localizedDescription: String { message }
}

// MARK: - Validate

/// Structural JSON Schema walker for CLIO contracts.
/// Handles the subset CLIO emits: object / array / string / number / integer /
/// boolean / null, required, enum, minLength / maxLength, minimum / maximum,
/// array items, anyOf (Optional<T>), and the x-clio-assert predicate list.
enum Validate {

    /// Encode `value` to JSON, then walk it against `schemaJSON`.
    /// Throws `ValidationError` on the first violation found.
    static func check<T: Encodable>(_ value: T, against schemaJSON: String) throws {
        let encoder = JSONEncoder()
        let data = try encoder.encode(value)
        guard let instance = try? JSONSerialization.jsonObject(with: data),
              let obj = instance as? [String: Any] else {
            throw ValidationError(message: "root value must encode to a JSON object")
        }
        guard let schemaData = schemaJSON.data(using: .utf8),
              let schemaAny = try? JSONSerialization.jsonObject(with: schemaData),
              let schema = schemaAny as? [String: Any] else {
            throw ValidationError(message: "invalid schema JSON")
        }
        try validateObject(obj, schema: schema)
    }

    // MARK: - Structural walkers

    private static func validateValue(_ value: Any, schema: [String: Any]) throws {
        // anyOf — Optional<T> emits {"anyOf": [<T-schema>, {"type": "null"}]}
        if let anyOf = schema["anyOf"] as? [Any] {
            for branchAny in anyOf {
                guard let branch = branchAny as? [String: Any] else { continue }
                if (try? validateValue(value, schema: branch)) != nil { return }
            }
            throw ValidationError(message: "value does not match anyOf")
        }

        guard let type = schema["type"] as? String else {
            // No type key: only enum constraint applies.
            if let enumVals = schema["enum"] as? [Any],
               let sv = value as? String {
                let strs = enumVals.compactMap { $0 as? String }
                if !strs.contains(sv) {
                    throw ValidationError(message: "'\(sv)' not in enum \(strs)")
                }
            }
            return
        }

        switch type {
        case "object":
            guard let obj = value as? [String: Any] else {
                throw ValidationError(message: "expected object")
            }
            try validateObject(obj, schema: schema)

        case "array":
            guard let arr = value as? [Any] else {
                throw ValidationError(message: "expected array")
            }
            if let itemSchemaAny = schema["items"],
               let itemSchema = itemSchemaAny as? [String: Any] {
                for item in arr { try validateValue(item, schema: itemSchema) }
            }

        case "string":
            guard let sv = value as? String else {
                throw ValidationError(message: "expected string")
            }
            if let maxLen = (schema["maxLength"] as? NSNumber)?.intValue, sv.count > maxLen {
                throw ValidationError(
                    message: "string length \(sv.count) > maxLength \(maxLen)")
            }
            if let minLen = (schema["minLength"] as? NSNumber)?.intValue, sv.count < minLen {
                throw ValidationError(
                    message: "string length \(sv.count) < minLength \(minLen)")
            }
            if let enumVals = schema["enum"] as? [Any] {
                let strs = enumVals.compactMap { $0 as? String }
                if !strs.isEmpty && !strs.contains(sv) {
                    throw ValidationError(message: "'\(sv)' not in enum \(strs)")
                }
            }

        case "integer", "number":
            guard let nv = toDouble(value) else {
                throw ValidationError(message: "expected number")
            }
            if let min = (schema["minimum"] as? NSNumber)?.doubleValue, nv < min {
                throw ValidationError(message: "\(nv) < minimum \(min)")
            }
            if let max = (schema["maximum"] as? NSNumber)?.doubleValue, nv > max {
                throw ValidationError(message: "\(nv) > maximum \(max)")
            }

        case "boolean":
            // JSONSerialization returns booleans as NSNumber on Apple platforms.
            if value is NSNull {
                throw ValidationError(message: "expected boolean, got null")
            }

        case "null":
            if !(value is NSNull) {
                throw ValidationError(message: "expected null")
            }

        default:
            break
        }
    }

    private static func validateObject(_ obj: [String: Any], schema: [String: Any]) throws {
        // required fields
        if let required = schema["required"] as? [Any] {
            for keyAny in required {
                guard let key = keyAny as? String else { continue }
                if obj[key] == nil {
                    throw ValidationError(message: "missing required field '\(key)'")
                }
            }
        }
        // property constraints
        if let props = schema["properties"] as? [String: Any] {
            for (key, propAny) in props {
                guard let propSchema = propAny as? [String: Any],
                      let val = obj[key] else { continue }
                try validateValue(val, schema: propSchema)
            }
        }
        // x-clio-assert — walks the compact CLIO assert AST (same as Go runtime)
        if let assertNode = schema["x-clio-assert"] {
            if !evalAssert(assertNode, ctx: obj) {
                throw ValidationError(message: "x-clio-assert failed")
            }
        }
    }

    // MARK: - Assert walker (mirrors evalAssert in Go and Python runtimes)
    // Node kinds: ident, int, float, str, call(len, ...), compare, bool_and.
    // Any unrecognised kind is treated as false (defensive).

    private static func evalAssert(_ node: Any, ctx: Any) -> Bool {
        guard let m = node as? [String: Any],
              let kind = m["kind"] as? String else { return false }
        switch kind {
        case "ident":
            guard let name = m["name"] as? String,
                  let obj = ctx as? [String: Any] else { return false }
            return obj[name] != nil
        case "int", "float", "str":
            return true
        case "call":
            guard let fn = m["func"] as? String, fn == "len",
                  let args = m["args"] as? [Any], args.count == 1 else { return false }
            return lenOf(args[0], ctx: ctx) >= 0
        case "compare":
            guard let leftNode = m["left"], let rightNode = m["right"],
                  let op = m["op"] as? String else { return false }
            return cmpOk(resolveNode(leftNode, ctx: ctx),
                         resolveNode(rightNode, ctx: ctx), op: op)
        case "bool_and":
            guard let l = m["left"], let r = m["right"] else { return false }
            return evalAssert(l, ctx: ctx) && evalAssert(r, ctx: ctx)
        default:
            return false
        }
    }

    private static func resolveNode(_ node: Any, ctx: Any) -> Any? {
        guard let m = node as? [String: Any],
              let kind = m["kind"] as? String else { return nil }
        switch kind {
        case "ident":
            guard let name = m["name"] as? String,
                  let obj = ctx as? [String: Any] else { return nil }
            return obj[name]
        case "int", "float":
            return m["value"]       // NSNumber from JSONSerialization
        case "str":
            return m["value"]       // String
        case "call":
            guard let fn = m["func"] as? String, fn == "len",
                  let args = m["args"] as? [Any], args.count == 1 else { return nil }
            return lenOf(args[0], ctx: ctx)     // Swift Int
        default:
            return nil
        }
    }

    private static func lenOf(_ node: Any, ctx: Any) -> Int {
        switch resolveNode(node, ctx: ctx) {
        case let s as String:       return s.count
        case let a as [Any]:        return a.count
        case let d as [String: Any]: return d.count
        default:                    return -1
        }
    }

    private static func cmpOk(_ l: Any?, _ r: Any?, op: String) -> Bool {
        if let lf = toDouble(l), let rf = toDouble(r) {
            switch op {
            case "==": return lf == rf
            case "!=": return lf != rf
            case "<":  return lf < rf
            case ">":  return lf > rf
            case "<=": return lf <= rf
            case ">=": return lf >= rf
            default:   return false
            }
        }
        if let ls = l as? String, let rs = r as? String {
            switch op {
            case "==": return ls == rs
            case "!=": return ls != rs
            default:   return false
            }
        }
        return false
    }

    /// Convert Any to Double for numeric comparison.
    /// NSNumber covers JSON-parsed numbers; Int covers lenOf() results.
    private static func toDouble(_ v: Any?) -> Double? {
        guard let v else { return nil }
        if let n = v as? NSNumber { return n.doubleValue }
        if let n = v as? Int { return Double(n) }
        return nil
    }
}
"""


def render_runtime_validate_swift() -> str:
    """Return the body of Sources/ClioFlow/Runtime/Validate.swift.

    Static template — no per-emission substitution. Emitted only when
    the flow uses at least one contract. Uses only Foundation —
    zero external dependencies."""
    return _VALIDATE_SWIFT_TEMPLATE


# ---------------------------------------------------------------------------
# Anthropic.swift — zero-dep Anthropic Messages API client
# ---------------------------------------------------------------------------

# NOTE: the raw-string prefix keeps Swift's \(preview) string interpolation
# syntax and Swift \n escape sequences intact — Python does NOT process them.
_ANTHROPIC_SWIFT_TEMPLATE = r"""// Auto-generated by CLIO. Do not edit by hand.
// Zero-dependency Anthropic Messages API client for judgment steps.
// Uses Foundation (URLSession) only — no external SDKs.
// Cross-platform: imports FoundationNetworking on Linux where URLSession lives.
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Foundation

// MARK: - AnthropicError

struct AnthropicError: Error {
    let message: String
    var localizedDescription: String { message }
}

// MARK: - Anthropic

/// Thin URLSession wrapper over the Anthropic Messages API.
/// Returns the text content of the first content block.
enum Anthropic {

    /// Call the Anthropic Messages API and return the assistant's text reply.
    ///
    /// - Parameters:
    ///   - model:     Anthropic model ID (e.g. "claude-haiku-4-5-20251001")
    ///   - system:    System-prompt text (the JSON-only directive)
    ///   - prompt:    User-turn text (the serialised step input)
    ///   - maxTokens: Maximum tokens to generate
    /// - Returns: The raw text from `response.content[0].text`
    /// - Throws:  `AnthropicError` when the API key is missing, the HTTP call
    ///            fails, or the response shape is unexpected.
    static func complete(
        model: String,
        system: String,
        prompt: String,
        maxTokens: Int
    ) async throws -> String {
        guard let apiKey = ProcessInfo.processInfo.environment["ANTHROPIC_API_KEY"],
              !apiKey.isEmpty else {
            throw AnthropicError(message: "ANTHROPIC_API_KEY is not set or is empty")
        }

        guard let url = URL(string: "https://api.anthropic.com/v1/messages") else {
            throw AnthropicError(message: "internal: invalid Anthropic API URL")
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(apiKey, forHTTPHeaderField: "x-api-key")
        request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        request.setValue("application/json", forHTTPHeaderField: "content-type")

        let body: [String: Any] = [
            "model": model,
            "max_tokens": maxTokens,
            "system": system,
            "messages": [["role": "user", "content": prompt]]
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        return try await withCheckedThrowingContinuation { continuation in
            URLSession.shared.dataTask(with: request) { data, _, error in
                if let error = error {
                    continuation.resume(throwing: error)
                    return
                }
                guard let data = data else {
                    continuation.resume(throwing: AnthropicError(
                        message: "Anthropic: empty response body"))
                    return
                }
                do {
                    guard
                        let json = try JSONSerialization.jsonObject(with: data)
                            as? [String: Any],
                        let content = json["content"] as? [[String: Any]],
                        let first = content.first,
                        let text = first["text"] as? String
                    else {
                        let preview = String(data: data.prefix(200), encoding: .utf8)
                            ?? "<non-UTF8>"
                        throw AnthropicError(
                            message: "Anthropic: unexpected response shape: \(preview)")
                    }
                    continuation.resume(returning: text)
                } catch {
                    continuation.resume(throwing: error)
                }
            }.resume()
        }
    }
}
"""


def render_runtime_anthropic_swift() -> str:
    """Return the body of Sources/ClioFlow/Runtime/Anthropic.swift.

    Static template — no per-emission substitution. Emitted only when
    the flow uses at least one judgment step. Uses only Foundation —
    zero external dependencies."""
    return _ANTHROPIC_SWIFT_TEMPLATE
