"""Static Swift runtime templates emitted under Sources/ClioFlow/Runtime/.

These are pure Swift source strings: no per-graph substitution.
`render_runtime_validate_swift` returns the Validate.swift content verbatim.

Why a separate module: mirrors the pattern of _go_runtime_templates.py, keeping
_swift_helpers.py focused on graph-bound rendering.
"""
from __future__ import annotations

# NOTE: this is a Python raw string (r-prefix) so that Swift's \(interpolation)
# syntax passes through unmodified — Python does NOT process the backslash sequences.
_VALIDATE_SWIFT_TEMPLATE = r"""// Auto-generated by CLIO. Do not edit by hand.
// Zero-dependency structural validator for CLIO contract schemas.
// Mirrors clio/runtime/validate.py and clio/emitters/_go_runtime_templates.py
// but uses only Foundation (JSONEncoder + JSONSerialization) — no external deps.
import Foundation

// MARK: - ValidationError

struct ValidationError: Error {
    let message: String
    var localizedDescription: String { message }
}

// MARK: - Validate

/// Structural JSON Schema walker for CLIO contracts.
/// Handles the subset CLIO emits: object / array / string / number / integer /
/// boolean / null, required, enum, minLength / maxLength, minimum / maximum,
/// array items, anyOf (Optional<T>), and the x-clio-assert predicate list.
enum Validate {

    /// Encode `value` to JSON, then walk it against `schemaJSON`.
    /// Throws `ValidationError` on the first violation found.
    static func check<T: Encodable>(_ value: T, against schemaJSON: String) throws {
        let encoder = JSONEncoder()
        let data = try encoder.encode(value)
        guard let instance = try? JSONSerialization.jsonObject(with: data),
              let obj = instance as? [String: Any] else {
            throw ValidationError(message: "root value must encode to a JSON object")
        }
        guard let schemaData = schemaJSON.data(using: .utf8),
              let schemaAny = try? JSONSerialization.jsonObject(with: schemaData),
              let schema = schemaAny as? [String: Any] else {
            throw ValidationError(message: "invalid schema JSON")
        }
        try validateObject(obj, schema: schema)
    }

    // MARK: - Structural walkers

    private static func validateValue(_ value: Any, schema: [String: Any]) throws {
        // anyOf — Optional<T> emits {"anyOf": [<T-schema>, {"type": "null"}]}
        if let anyOf = schema["anyOf"] as? [Any] {
            for branchAny in anyOf {
                guard let branch = branchAny as? [String: Any] else { continue }
                if (try? validateValue(value, schema: branch)) != nil { return }
            }
            throw ValidationError(message: "value does not match anyOf")
        }

        guard let type = schema["type"] as? String else {
            // No type key: only enum constraint applies.
            if let enumVals = schema["enum"] as? [Any],
               let sv = value as? String {
                let strs = enumVals.compactMap { $0 as? String }
                if !strs.contains(sv) {
                    throw ValidationError(message: "'\(sv)' not in enum \(strs)")
                }
            }
            return
        }

        switch type {
        case "object":
            guard let obj = value as? [String: Any] else {
                throw ValidationError(message: "expected object")
            }
            try validateObject(obj, schema: schema)

        case "array":
            guard let arr = value as? [Any] else {
                throw ValidationError(message: "expected array")
            }
            if let itemSchemaAny = schema["items"],
               let itemSchema = itemSchemaAny as? [String: Any] {
                for item in arr { try validateValue(item, schema: itemSchema) }
            }

        case "string":
            guard let sv = value as? String else {
                throw ValidationError(message: "expected string")
            }
            if let maxLen = (schema["maxLength"] as? NSNumber)?.intValue, sv.count > maxLen {
                throw ValidationError(
                    message: "string length \(sv.count) > maxLength \(maxLen)")
            }
            if let minLen = (schema["minLength"] as? NSNumber)?.intValue, sv.count < minLen {
                throw ValidationError(
                    message: "string length \(sv.count) < minLength \(minLen)")
            }
            if let enumVals = schema["enum"] as? [Any] {
                let strs = enumVals.compactMap { $0 as? String }
                if !strs.isEmpty && !strs.contains(sv) {
                    throw ValidationError(message: "'\(sv)' not in enum \(strs)")
                }
            }

        case "integer", "number":
            guard let nv = toDouble(value) else {
                throw ValidationError(message: "expected number")
            }
            if let min = (schema["minimum"] as? NSNumber)?.doubleValue, nv < min {
                throw ValidationError(message: "\(nv) < minimum \(min)")
            }
            if let max = (schema["maximum"] as? NSNumber)?.doubleValue, nv > max {
                throw ValidationError(message: "\(nv) > maximum \(max)")
            }

        case "boolean":
            // JSONSerialization returns booleans as NSNumber on Apple platforms.
            if value is NSNull {
                throw ValidationError(message: "expected boolean, got null")
            }

        case "null":
            if !(value is NSNull) {
                throw ValidationError(message: "expected null")
            }

        default:
            break
        }
    }

    private static func validateObject(_ obj: [String: Any], schema: [String: Any]) throws {
        // required fields
        if let required = schema["required"] as? [Any] {
            for keyAny in required {
                guard let key = keyAny as? String else { continue }
                if obj[key] == nil {
                    throw ValidationError(message: "missing required field '\(key)'")
                }
            }
        }
        // property constraints
        if let props = schema["properties"] as? [String: Any] {
            for (key, propAny) in props {
                guard let propSchema = propAny as? [String: Any],
                      let val = obj[key] else { continue }
                try validateValue(val, schema: propSchema)
            }
        }
        // x-clio-assert — walks the compact CLIO assert AST (same as Go runtime)
        if let assertNode = schema["x-clio-assert"] {
            if !evalAssert(assertNode, ctx: obj) {
                throw ValidationError(message: "x-clio-assert failed")
            }
        }
    }

    // MARK: - Assert walker (mirrors evalAssert in Go and Python runtimes)
    // Node kinds: ident, int, float, str, call(len, ...), compare, bool_and.
    // Any unrecognised kind is treated as false (defensive).

    private static func evalAssert(_ node: Any, ctx: Any) -> Bool {
        guard let m = node as? [String: Any],
              let kind = m["kind"] as? String else { return false }
        switch kind {
        case "ident":
            guard let name = m["name"] as? String,
                  let obj = ctx as? [String: Any] else { return false }
            return obj[name] != nil
        case "int", "float", "str":
            return true
        case "call":
            guard let fn = m["func"] as? String, fn == "len",
                  let args = m["args"] as? [Any], args.count == 1 else { return false }
            return lenOf(args[0], ctx: ctx) >= 0
        case "compare":
            guard let leftNode = m["left"], let rightNode = m["right"],
                  let op = m["op"] as? String else { return false }
            return cmpOk(resolveNode(leftNode, ctx: ctx),
                         resolveNode(rightNode, ctx: ctx), op: op)
        case "bool_and":
            guard let l = m["left"], let r = m["right"] else { return false }
            return evalAssert(l, ctx: ctx) && evalAssert(r, ctx: ctx)
        default:
            return false
        }
    }

    private static func resolveNode(_ node: Any, ctx: Any) -> Any? {
        guard let m = node as? [String: Any],
              let kind = m["kind"] as? String else { return nil }
        switch kind {
        case "ident":
            guard let name = m["name"] as? String,
                  let obj = ctx as? [String: Any] else { return nil }
            return obj[name]
        case "int", "float":
            return m["value"]       // NSNumber from JSONSerialization
        case "str":
            return m["value"]       // String
        case "call":
            guard let fn = m["func"] as? String, fn == "len",
                  let args = m["args"] as? [Any], args.count == 1 else { return nil }
            return lenOf(args[0], ctx: ctx)     // Swift Int
        default:
            return nil
        }
    }

    private static func lenOf(_ node: Any, ctx: Any) -> Int {
        switch resolveNode(node, ctx: ctx) {
        case let s as String:       return s.count
        case let a as [Any]:        return a.count
        case let d as [String: Any]: return d.count
        default:                    return -1
        }
    }

    private static func cmpOk(_ l: Any?, _ r: Any?, op: String) -> Bool {
        // Bool does not bridge to NSNumber on Linux; handle it before the
        // toDouble path so cross-platform bool comparisons work.
        if let lb = l as? Bool, let rb = r as? Bool {
            switch op {
            case "==": return lb == rb
            case "!=": return lb != rb
            default:   return false
            }
        }
        if let lf = toDouble(l), let rf = toDouble(r) {
            switch op {
            case "==": return lf == rf
            case "!=": return lf != rf
            case "<":  return lf < rf
            case ">":  return lf > rf
            case "<=": return lf <= rf
            case ">=": return lf >= rf
            default:   return false
            }
        }
        if let ls = l as? String, let rs = r as? String {
            switch op {
            case "==": return ls == rs
            case "!=": return ls != rs
            default:   return false
            }
        }
        return false
    }

    /// Convert Any to Double for numeric comparison.
    /// NSNumber covers JSON-parsed numbers; Int covers lenOf() results.
    private static func toDouble(_ v: Any?) -> Double? {
        guard let v else { return nil }
        if let n = v as? NSNumber { return n.doubleValue }
        if let n = v as? Int { return Double(n) }
        return nil
    }
}
"""


def render_runtime_validate_swift() -> str:
    """Return the body of Sources/ClioFlow/Runtime/Validate.swift.

    Static template — no per-emission substitution. Emitted only when
    the flow uses at least one contract. Uses only Foundation —
    zero external dependencies."""
    return _VALIDATE_SWIFT_TEMPLATE


# ---------------------------------------------------------------------------
# Anthropic.swift — zero-dep Anthropic Messages API client
# ---------------------------------------------------------------------------

# NOTE: the raw-string prefix keeps Swift's \(preview) string interpolation
# syntax and Swift \n escape sequences intact — Python does NOT process them.
_ANTHROPIC_SWIFT_TEMPLATE = r"""// Auto-generated by CLIO. Do not edit by hand.
// Zero-dependency Anthropic Messages API client for judgment steps.
// Uses Foundation (URLSession) only — no external SDKs.
// Cross-platform: imports FoundationNetworking on Linux where URLSession lives.
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Foundation

// MARK: - AnthropicError

struct AnthropicError: Error {
    let message: String
    var localizedDescription: String { message }
}

// MARK: - Anthropic

/// Thin URLSession wrapper over the Anthropic Messages API.
/// Returns the text content of the first content block.
enum Anthropic {

    /// Call the Anthropic Messages API and return the assistant's text reply.
    ///
    /// - Parameters:
    ///   - model:     Anthropic model ID (e.g. "claude-haiku-4-5-20251001")
    ///   - system:    System-prompt text (the JSON-only directive)
    ///   - prompt:    User-turn text (the serialised step input)
    ///   - maxTokens: Maximum tokens to generate
    /// - Returns: The raw text from `response.content[0].text`
    /// - Throws:  `AnthropicError` when the API key is missing, the HTTP call
    ///            fails, or the response shape is unexpected.
    static func complete(
        model: String,
        system: String,
        prompt: String,
        maxTokens: Int
    ) async throws -> String {
        guard let apiKey = ProcessInfo.processInfo.environment["ANTHROPIC_API_KEY"],
              !apiKey.isEmpty else {
            throw AnthropicError(message: "ANTHROPIC_API_KEY is not set or is empty")
        }

        guard let url = URL(string: "https://api.anthropic.com/v1/messages") else {
            throw AnthropicError(message: "internal: invalid Anthropic API URL")
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(apiKey, forHTTPHeaderField: "x-api-key")
        request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        request.setValue("application/json", forHTTPHeaderField: "content-type")

        let body: [String: Any] = [
            "model": model,
            "max_tokens": maxTokens,
            "system": system,
            "messages": [["role": "user", "content": prompt]]
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        return try await withCheckedThrowingContinuation { continuation in
            URLSession.shared.dataTask(with: request) { data, _, error in
                if let error = error {
                    continuation.resume(throwing: error)
                    return
                }
                guard let data = data else {
                    continuation.resume(throwing: AnthropicError(
                        message: "Anthropic: empty response body"))
                    return
                }
                do {
                    guard let json = try JSONSerialization.jsonObject(with: data)
                            as? [String: Any] else {
                        let preview = String(data: data.prefix(200), encoding: .utf8)
                            ?? "<non-UTF8>"
                        throw AnthropicError(
                            message: "Anthropic: response is not a JSON object: \(preview)")
                    }
                    // Surface API-level error messages before attempting to parse content.
                    if let errObj = json["error"] as? [String: Any],
                       let errMsg = errObj["message"] as? String {
                        throw AnthropicError(message: "Anthropic API error: \(errMsg)")
                    }
                    guard let content = json["content"] as? [[String: Any]],
                          let first = content.first,
                          let text = first["text"] as? String else {
                        let preview = String(data: data.prefix(200), encoding: .utf8)
                            ?? "<non-UTF8>"
                        throw AnthropicError(
                            message: "Anthropic: unexpected response shape: \(preview)")
                    }
                    continuation.resume(returning: text)
                } catch {
                    continuation.resume(throwing: error)
                }
            }.resume()
        }
    }
}
"""


def render_runtime_anthropic_swift() -> str:
    """Return the body of Sources/ClioFlow/Runtime/Anthropic.swift.

    Static template — no per-emission substitution. Emitted only when
    the flow uses at least one judgment step. Uses only Foundation —
    zero external dependencies."""
    return _ANTHROPIC_SWIFT_TEMPLATE


# ---------------------------------------------------------------------------
# SHA256.swift — vendored pure-Swift FIPS 180-4 implementation
# ---------------------------------------------------------------------------

# NOTE: raw string — Python does NOT process backslash sequences inside.
_SHA256_SWIFT_TEMPLATE = r"""// Auto-generated by CLIO. Do not edit by hand.
// FIPS 180-4 SHA-256 — vendored pure-Swift implementation.
// No CryptoKit, no CommonCrypto — byte-stable on all platforms.
//
// Public API:
//   sha256Hex(_ bytes: [UInt8]) -> String
//   sha256Hex(_ s: String)      -> String

// MARK: - Round constants (fractional parts of cube roots of first 64 primes)

private let _k256: [UInt32] = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
    0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
    0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
    0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
    0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
    0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

// MARK: - Public API

/// Return the lowercase hex-encoded SHA-256 digest of `bytes`.
func sha256Hex(_ bytes: [UInt8]) -> String {
    var chars = [Character]()
    chars.reserveCapacity(64)
    for b in _sha256Digest(bytes) {
        let hi = UInt32(b >> 4)
        let lo = UInt32(b & 0xf)
        // 48 = '0', 97 = 'a'; 87 = 97 - 10
        chars.append(Character(UnicodeScalar(hi < 10 ? 48 + hi : 87 + hi)!))
        chars.append(Character(UnicodeScalar(lo < 10 ? 48 + lo : 87 + lo)!))
    }
    return String(chars)
}

/// Return the lowercase hex-encoded SHA-256 digest of the UTF-8 encoding of `s`.
func sha256Hex(_ s: String) -> String {
    sha256Hex([UInt8](s.utf8))
}

// MARK: - Internal

private func _rotr32(_ x: UInt32, _ n: UInt32) -> UInt32 {
    (x >> n) | (x << (32 &- n))
}

private func _sha256Digest(_ message: [UInt8]) -> [UInt8] {
    // Initial hash values (fractional parts of square roots of first 8 primes)
    var h0: UInt32 = 0x6a09e667
    var h1: UInt32 = 0xbb67ae85
    var h2: UInt32 = 0x3c6ef372
    var h3: UInt32 = 0xa54ff53a
    var h4: UInt32 = 0x510e527f
    var h5: UInt32 = 0x9b05688c
    var h6: UInt32 = 0x1f83d9ab
    var h7: UInt32 = 0x5be0cd19

    // Pre-processing: padding
    var msg = message
    let bitLen = UInt64(message.count) &* 8
    msg.append(0x80)
    while (msg.count % 64) != 56 {
        msg.append(0x00)
    }
    // Append original bit-length as 64-bit big-endian integer
    msg.append(UInt8((bitLen >> 56) & 0xff))
    msg.append(UInt8((bitLen >> 48) & 0xff))
    msg.append(UInt8((bitLen >> 40) & 0xff))
    msg.append(UInt8((bitLen >> 32) & 0xff))
    msg.append(UInt8((bitLen >> 24) & 0xff))
    msg.append(UInt8((bitLen >> 16) & 0xff))
    msg.append(UInt8((bitLen >>  8) & 0xff))
    msg.append(UInt8( bitLen        & 0xff))

    // Process each 64-byte (512-bit) block
    for blockStart in stride(from: 0, to: msg.count, by: 64) {
        var w = [UInt32](repeating: 0, count: 64)
        for i in 0..<16 {
            let b = blockStart + i * 4
            w[i] = (UInt32(msg[b])   << 24)
                 | (UInt32(msg[b+1]) << 16)
                 | (UInt32(msg[b+2]) <<  8)
                 |  UInt32(msg[b+3])
        }
        for i in 16..<64 {
            let s0 = _rotr32(w[i-15], 7) ^ _rotr32(w[i-15], 18) ^ (w[i-15] >> 3)
            let s1 = _rotr32(w[i-2], 17) ^ _rotr32(w[i-2], 19)  ^ (w[i-2]  >> 10)
            w[i] = w[i-16] &+ s0 &+ w[i-7] &+ s1
        }

        var a = h0, b = h1, c = h2, d = h3
        var e = h4, f = h5, g = h6, hh = h7

        for i in 0..<64 {
            let S1    = _rotr32(e, 6)  ^ _rotr32(e, 11) ^ _rotr32(e, 25)
            let ch    = (e & f) ^ (~e & g)
            let temp1 = hh &+ S1 &+ ch &+ _k256[i] &+ w[i]
            let S0    = _rotr32(a, 2)  ^ _rotr32(a, 13) ^ _rotr32(a, 22)
            let maj   = (a & b) ^ (a & c) ^ (b & c)
            let temp2 = S0 &+ maj
            hh = g; g = f; f = e
            e  = d &+ temp1
            d  = c; c = b; b = a
            a  = temp1 &+ temp2
        }

        h0 = h0 &+ a; h1 = h1 &+ b; h2 = h2 &+ c; h3 = h3 &+ d
        h4 = h4 &+ e; h5 = h5 &+ f; h6 = h6 &+ g; h7 = h7 &+ hh
    }

    // Produce final 32-byte digest (big-endian)
    var digest = [UInt8](repeating: 0, count: 32)
    for (i, h) in [h0, h1, h2, h3, h4, h5, h6, h7].enumerated() {
        digest[i * 4]     = UInt8((h >> 24) & 0xff)
        digest[i * 4 + 1] = UInt8((h >> 16) & 0xff)
        digest[i * 4 + 2] = UInt8((h >>  8) & 0xff)
        digest[i * 4 + 3] = UInt8( h        & 0xff)
    }
    return digest
}
"""


def render_runtime_sha256_swift() -> str:
    """Return the body of Sources/ClioFlow/Runtime/SHA256.swift.

    Static template — no per-emission substitution. Emitted only when
    the flow uses cache. Pure-Swift FIPS 180-4 implementation, no CryptoKit —
    byte-stable across all platforms (no #if canImport(CryptoKit))."""
    return _SHA256_SWIFT_TEMPLATE


# ---------------------------------------------------------------------------
# Cache.swift — content-addressed cache (byte-identical layout to cache.py)
# ---------------------------------------------------------------------------

# NOTE: raw string — \n and \(interpolation) inside Swift string literals pass
# through unmodified because Python does NOT process them in r-strings.
_CACHE_SWIFT_TEMPLATE = r"""// Auto-generated by CLIO. Do not edit by hand.
// Cache layout matches clio/runtime/cache.py and clio_runtime/cache/cache.go
// byte-for-byte so cache files are interchangeable across targets.
//
// Key derivation (identical to Python and Go targets):
//   SHA256(step + "\n" + model + "\n" + prompt + "\n" + schemaJSON)
//
// On disk: <cache_dir>/<step_name>/<sha256>.json
//   {"created_at": <epoch>, "model": "<m>", "response": "<raw>"}
import Foundation

// MARK: - Cache

enum Cache {

    /// Derive the cache key.
    /// Formula is byte-identical to clio/runtime/cache.py::cache_key and
    /// clio_runtime/cache/cache.go::Key.
    static func key(step: String, model: String, prompt: String, schema: String) -> String {
        let payload = [step, model, prompt, schema].joined(separator: "\n")
        return sha256Hex(payload)
    }

    /// Return the cached response string, or nil on miss or staleness.
    ///
    /// - Parameters:
    ///   - ttlSeconds: nil for permanent (CACHE: on); positive integer for TTL (CACHE: ttl(…))
    static func lookup(
        cacheDir: String,
        stepName: String,
        key: String,
        ttlSeconds: Int?
    ) -> String? {
        let path = URL(fileURLWithPath: cacheDir)
            .appendingPathComponent(stepName)
            .appendingPathComponent("\(key).json")
        guard
            let data = try? Data(contentsOf: path),
            let obj  = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
            let response = obj["response"] as? String
        else { return nil }
        if let ttl = ttlSeconds {
            let createdAt = (obj["created_at"] as? NSNumber)?.doubleValue ?? 0.0
            let age = Date().timeIntervalSince1970 - createdAt
            if age >= Double(ttl) { return nil }
        }
        return response
    }

    /// Write a cache entry atomically (write to .tmp then rename).
    static func store(
        cacheDir: String,
        stepName: String,
        key: String,
        model: String,
        response: String
    ) {
        let dir = URL(fileURLWithPath: cacheDir).appendingPathComponent(stepName)
        try? FileManager.default.createDirectory(
            at: dir, withIntermediateDirectories: true, attributes: nil
        )
        let final = dir.appendingPathComponent("\(key).json")
        let tmp   = dir.appendingPathComponent("\(key).json.tmp")
        let entry: [String: Any] = [
            "created_at": Int(Date().timeIntervalSince1970),
            "model":      model,
            "response":   response,
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: entry) else { return }
        try? data.write(to: tmp)
        // moveItem fails if the destination exists; remove a stale entry first
        // so a refreshed cache value (e.g. after TTL expiry) overwrites it.
        if FileManager.default.fileExists(atPath: final.path) {
            try? FileManager.default.removeItem(at: final)
        }
        try? FileManager.default.moveItem(at: tmp, to: final)
    }

    /// Return CLIO_CACHE_DIR env var or ".cache" — mirrors CacheDirFromEnv() in cache.go.
    static func cacheDirFromEnv() -> String {
        ProcessInfo.processInfo.environment["CLIO_CACHE_DIR"] ?? ".cache"
    }
}
"""


def render_runtime_cache_swift() -> str:
    """Return the body of Sources/ClioFlow/Runtime/Cache.swift.

    Static template — no per-emission substitution. Emitted only when
    the flow uses at least one judgment step with an active CACHE directive.
    Key derivation is byte-identical to clio/runtime/cache.py::cache_key
    and clio_runtime/cache/cache.go::Key."""
    return _CACHE_SWIFT_TEMPLATE
