from pathlib import Path

from clio.emitters.base import BaseEmitter
from clio.ir.graph import FlowGraph, StepIR


_CLAUDE_MD = """# CLIO-emitted project

Generated from a .clio source by the CLIO compiler v0.1.

This project is self-contained. Run with `bash run.sh` (added at a later phase).
"""


_STEP_TEMPLATE = '''"""Step: {name} (mode={mode})

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import json
import sys


def main() -> int:
    # TODO: implement step body once TAKES/GIVES are added.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


class ClaudeCLIEmitter(BaseEmitter):
    def emit(self, graph: FlowGraph, output_dir: Path) -> None:
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "CLAUDE.md").write_text(_CLAUDE_MD)

        claude_dir = output_dir / ".claude"
        claude_dir.mkdir(exist_ok=True)
        (claude_dir / "hooks.json").write_text("{}")

        steps_dir = output_dir / "steps"
        steps_dir.mkdir(exist_ok=True)
        for idx, step in enumerate(graph.steps, start=1):
            self._emit_step(steps_dir, idx, step)

    @staticmethod
    def _emit_step(steps_dir: Path, idx: int, step: StepIR) -> None:
        filename = f"{idx:02d}_{step.name}.py"
        body = _STEP_TEMPLATE.format(name=step.name, mode=step.mode)
        (steps_dir / filename).write_text(body)
