import json
import shlex
from pathlib import Path

from clio.emitters.base import BaseEmitter
from clio.ir.contracts import type_to_json_schema
from clio.ir.graph import ContractIR, FieldIR, FlowGraph, StepIR
from clio.parser.ast_nodes import PrimitiveType


_CLAUDE_MD = """# CLIO-emitted project

Generated from a .clio source by the CLIO compiler v0.1.

This project is self-contained. Run with `bash run.sh` (added at a later phase).
"""


_STEP_NO_FIELDS = '''"""Step: {name} (mode={mode})

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import json
import sys


def main() -> int:
    # TODO: implement step body once TAKES/GIVES are added.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_EXACT_STEP_TEMPLATE = '''"""Step: {name} (mode={mode})

{io_doc}

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import argparse
import json
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
{argparse_block}
    args = parser.parse_args()

    {body}

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {{}}
    state["{out_name}"] = {out_name}
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_JUDGMENT_PROMPT_TEMPLATE = """You are executing the CLIO step `{name}`.

Input:
{input_block}

Produce a JSON value that matches this schema:
${{schema}}

Respond with ONLY the JSON value, no prose.
"""


class ClaudeCLIEmitter(BaseEmitter):
    def emit(self, graph: FlowGraph, output_dir: Path) -> None:
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "CLAUDE.md").write_text(_CLAUDE_MD)

        claude_dir = output_dir / ".claude"
        claude_dir.mkdir(exist_ok=True)
        (claude_dir / "hooks.json").write_text("{}")

        if graph.contracts:
            contracts_dir = output_dir / "contracts"
            contracts_dir.mkdir(exist_ok=True)
            for c in graph.contracts:
                (contracts_dir / f"{c.name}.schema.json").write_text(
                    json.dumps(c.json_schema, indent=2) + "\n"
                )

        steps_dir = output_dir / "steps"
        steps_dir.mkdir(exist_ok=True)
        for idx, step in enumerate(graph.steps, start=1):
            self._emit_step(steps_dir, idx, step)

        if graph.flow is not None and all(
            self._step_for_call(graph, c).mode == "exact" for c in graph.flow.chain
        ):
            self._emit_run_sh_exact_only(graph, output_dir)

    @staticmethod
    def _step_for_call(graph: FlowGraph, call) -> StepIR:
        for s in graph.steps:
            if s.name == call.step_name:
                return s
        raise KeyError(call.step_name)

    def _emit_run_sh_exact_only(self, graph: FlowGraph, output_dir: Path) -> None:
        lines: list[str] = [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            'cd "$(dirname "$0")"',
            "echo '{}' > state.json",
            "",
        ]
        for idx, call in enumerate(graph.flow.chain, start=1):
            step = self._step_for_call(graph, call)
            args = self._render_kwargs_as_cli(call)
            lines.append(f"# Step {idx}: {step.name} (exact)")
            script_name = f"steps/{idx:02d}_{step.name}.py"
            lines.append(f"python {script_name} {args}")
            lines.append("")
        lines.append('echo "[clio] flow ' + graph.flow.name + ' completed."')
        run_path = output_dir / "run.sh"
        run_path.write_text("\n".join(lines) + "\n")
        run_path.chmod(0o755)

    @staticmethod
    def _render_kwargs_as_cli(call) -> str:
        parts: list[str] = []
        for name, value in call.kwargs:
            if isinstance(value, str) and value.startswith("@"):
                ref = value[1:]
                parts.append(f'--{name}="$(jq -r .{ref} state.json)"')
            else:
                parts.append(f'--{name}={shlex.quote(str(value))}')
        return " ".join(parts)

    @staticmethod
    def _emit_step(steps_dir: Path, idx: int, step: StepIR) -> None:
        prefix = f"{idx:02d}_{step.name}"
        if step.mode == "judgment":
            (steps_dir / f"{prefix}.prompt").write_text(_render_prompt(step))
            if step.gives is not None:
                schema = type_to_json_schema(step.gives.type)
                (steps_dir / f"{prefix}.schema.json").write_text(
                    json.dumps(schema, indent=2) + "\n"
                )
            return

        # exact step
        if not step.takes and step.gives is None:
            body = _STEP_NO_FIELDS.format(name=step.name, mode=step.mode)
        else:
            io_doc = "\n".join(_field_doc(f) for f in step.takes)
            if step.gives:
                io_doc += f"\nGIVES: {step.gives.name}: {_render_type(step.gives.type)}"
            argparse_block = "\n".join(
                f'    parser.add_argument("--{f.name}", required=True)'
                for f in step.takes
            )
            out_name = step.gives.name if step.gives else "result"
            assigned_from = step.takes[0].name if step.takes else '""'
            assignment = f"{out_name} = args.{assigned_from}  # echo: TODO replace with real logic"
            body = _EXACT_STEP_TEMPLATE.format(
                name=step.name,
                mode=step.mode,
                io_doc=io_doc,
                argparse_block=argparse_block,
                body=assignment,
                out_name=out_name,
            )
        (steps_dir / f"{prefix}.py").write_text(body)


def _render_prompt(step: StepIR) -> str:
    input_block = "\n".join(f"  {f.name}: ${{{f.name}}}" for f in step.takes) or "  (no inputs)"
    return _JUDGMENT_PROMPT_TEMPLATE.format(name=step.name, input_block=input_block)


def _field_doc(f: FieldIR) -> str:
    return f"TAKES: {f.name}: {_render_type(f.type)}"


def _render_type(t) -> str:
    if isinstance(t, PrimitiveType):
        return t.name
    return type(t).__name__
