import json
import shlex
from pathlib import Path

from clio.emitters.base import BaseEmitter
from clio.ir.contracts import type_to_json_schema
from clio.ir.graph import ContractIR, FieldIR, FlowGraph, StepIR
from clio.parser.ast_nodes import (
    ConstrainedType,
    ContractRef,
    EnumType,
    ListType,
    PrimitiveType,
    RecordType,
    TypeExpr,
)


def _inline_schema(t: TypeExpr, contracts_by_name: dict[str, ContractIR]) -> dict:
    """Resolve every ContractRef inline. Strips x-clio-assert from inlined contracts
    so the schema is plain JSON Schema (the assert remains on the on-disk version
    used by clio_runtime.validate)."""
    if isinstance(t, ContractRef):
        c = contracts_by_name.get(t.name)
        if c is None:
            return {"$ref": f"../contracts/{t.name}.schema.json"}
        schema = {k: v for k, v in c.json_schema.items() if k != "x-clio-assert"}
        return schema
    if isinstance(t, ListType):
        return {"type": "array", "items": _inline_schema(t.inner, contracts_by_name)}
    if isinstance(t, RecordType):
        return {
            "type": "object",
            "properties": {n: _inline_schema(ty, contracts_by_name) for n, ty in t.fields},
            "required": [n for n, _ in t.fields],
            "additionalProperties": False,
        }
    if isinstance(t, EnumType):
        return {"enum": list(t.values)}
    if isinstance(t, ConstrainedType):
        out = _inline_schema(t.base, contracts_by_name)
        for kind, value in t.constraints:
            if kind == "max":
                out["maxLength"] = value
        return out
    if isinstance(t, PrimitiveType):
        return type_to_json_schema(t)
    return type_to_json_schema(t)


_CLAUDE_MD = """# CLIO-emitted project

Generated from a .clio source by the CLIO compiler v0.1.

This project is self-contained. Run with `bash run.sh` (added at a later phase).
"""


_STEP_NO_FIELDS = '''"""Step: {name} (mode={mode})

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import json
import sys


def main() -> int:
    # TODO: implement step body once TAKES/GIVES are added.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_EXACT_STEP_TEMPLATE = '''"""Step: {name} (mode={mode})

{io_doc}

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import argparse
import json
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
{argparse_block}
    args = parser.parse_args()

    {body}

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {{}}
    state["{out_name}"] = {out_name}
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


_JUDGMENT_PROMPT_TEMPLATE = """You are executing the CLIO step `{name}`.

Input:
{input_block}

Produce a JSON value that EXACTLY matches this schema:
${{schema}}

Rules — these are non-negotiable:
1. Use EXACTLY the property names listed in the schema. Do NOT invent new fields.
2. Every required property must be present in every item.
3. For enum properties, use ONLY values from the listed enum.
4. Respect every constraint (maxLength, etc.).
5. Output the raw JSON value only. No markdown code fences. No prose. No explanation.
"""


class ClaudeCLIEmitter(BaseEmitter):
    def emit(self, graph: FlowGraph, output_dir: Path) -> None:
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "CLAUDE.md").write_text(_CLAUDE_MD)

        claude_dir = output_dir / ".claude"
        claude_dir.mkdir(exist_ok=True)
        (claude_dir / "hooks.json").write_text("{}")

        if graph.contracts:
            contracts_dir = output_dir / "contracts"
            contracts_dir.mkdir(exist_ok=True)
            for c in graph.contracts:
                (contracts_dir / f"{c.name}.schema.json").write_text(
                    json.dumps(c.json_schema, indent=2) + "\n"
                )

        steps_dir = output_dir / "steps"
        steps_dir.mkdir(exist_ok=True)
        for idx, step in enumerate(graph.steps, start=1):
            self._emit_step(steps_dir, idx, step)

        if graph.flow is not None:
            self._emit_run_sh(graph, output_dir)
            if any(
                self._step_for_call(graph, c).mode == "judgment"
                for c in graph.flow.chain
            ):
                self._copy_runtime(output_dir)

    def _copy_runtime(self, output_dir: Path) -> None:
        """Copy `clio.runtime.*` into the output as a top-level `clio_runtime/` package."""
        from clio import runtime as src_pkg
        src_dir = Path(src_pkg.__file__).parent
        dest = output_dir / "clio_runtime"
        dest.mkdir(exist_ok=True)
        for name in ("__init__.py", "validate.py", "substitute.py"):
            src_file = src_dir / name
            if src_file.exists():
                (dest / name).write_text(src_file.read_text())

    @staticmethod
    def _step_for_call(graph: FlowGraph, call) -> StepIR:
        for s in graph.steps:
            if s.name == call.step_name:
                return s
        raise KeyError(call.step_name)

    def _emit_run_sh(self, graph: FlowGraph, output_dir: Path) -> None:
        lines: list[str] = [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            'cd "$(dirname "$0")"',
            "",
            "# Resolve a Python 3.12+ interpreter (override with PYTHON env var if needed).",
            'PYTHON="${PYTHON:-}"',
            'if [ -z "$PYTHON" ]; then',
            "    for candidate in python3.12 python3.13 python3.14 python3 python; do",
            '        if command -v "$candidate" >/dev/null 2>&1 \\',
            "           && \"$candidate\" -c 'import sys; sys.exit(0 if sys.version_info >= (3,12) else 1)' >/dev/null 2>&1; then",
            '            PYTHON="$candidate"',
            "            break",
            "        fi",
            "    done",
            "fi",
            'if [ -z "$PYTHON" ]; then',
            '    echo "[clio] error: Python 3.12+ not found on PATH (set PYTHON=/path/to/python)" >&2',
            "    exit 1",
            "fi",
            "",
            "echo '{}' > state.json",
            "",
        ]
        model = (
            graph.resources.models[0]
            if graph.resources is not None and graph.resources.models
            else "haiku"
        )
        contracts_by_name = {c.name: c for c in graph.contracts}
        for idx, call in enumerate(graph.flow.chain, start=1):
            step = self._step_for_call(graph, call)
            if step.mode == "exact":
                args = self._render_kwargs_as_cli(call)
                script_name = f"steps/{idx:02d}_{step.name}.py"
                lines.append(f"# Step {idx}: {step.name} (exact)")
                lines.append(f'"$PYTHON" {script_name} {args}')
            else:
                lines.extend(self._render_judgment_step(
                    idx, step, call, model=model,
                    contracts_by_name=contracts_by_name,
                ))
            lines.append("")
        lines.append('echo "[clio] flow ' + graph.flow.name + ' completed."')
        run_path = output_dir / "run.sh"
        run_path.write_text("\n".join(lines) + "\n")
        run_path.chmod(0o755)

    def _render_judgment_step(
        self,
        idx: int,
        step: StepIR,
        call,
        model: str,
        contracts_by_name: dict[str, ContractIR],
    ) -> list[str]:
        prompt_path = f"steps/{idx:02d}_{step.name}.prompt"
        schema_path = f"steps/{idx:02d}_{step.name}.schema.json"
        out_name = step.gives.name if step.gives else "result"
        # Build the inlined schema (resolved $refs, no x-clio-assert) for the LLM prompt.
        # The on-disk schema_path keeps the $ref + x-clio-assert form for validate.py.
        inlined = _inline_schema(step.gives.type, contracts_by_name) if step.gives else {}
        inlined_json = json.dumps(inlined, separators=(",", ":"))
        return [
            f"# Step {idx}: {step.name} (judgment)",
            f"INLINED_SCHEMA_{idx:02d}={shlex.quote(inlined_json)}",
            f'PROMPT="$("$PYTHON" -m clio_runtime.substitute {prompt_path} state.json)"',
            f'PROMPT="${{PROMPT//\\$\\{{schema\\}}/$INLINED_SCHEMA_{idx:02d}}}"',
            f'RAW_RESPONSE="$(printf %s "$PROMPT" | claude -p --model {model} --output-format text)"',
            f'if [ -z "$RAW_RESPONSE" ]; then echo "[clio] empty response from claude -p in step {idx} ({step.name})" >&2; exit 1; fi',
            f"RESPONSE=\"$(printf %s \"$RAW_RESPONSE\" | awk '!/^```/')\"",
            f'printf %s "$RESPONSE" | "$PYTHON" -m clio_runtime.validate {schema_path} -',
            f"jq --argjson r \"$RESPONSE\" '.{out_name} = $r' state.json > state.json.tmp && mv state.json.tmp state.json",
        ]

    @staticmethod
    def _render_kwargs_as_cli(call) -> str:
        parts: list[str] = []
        for name, value in call.kwargs:
            if isinstance(value, str) and value.startswith("@"):
                ref = value[1:]
                parts.append(f'--{name}="$(jq -r .{ref} state.json)"')
            else:
                parts.append(f'--{name}={shlex.quote(str(value))}')
        return " ".join(parts)

    @staticmethod
    def _emit_step(steps_dir: Path, idx: int, step: StepIR) -> None:
        prefix = f"{idx:02d}_{step.name}"
        if step.mode == "judgment":
            (steps_dir / f"{prefix}.prompt").write_text(_render_prompt(step))
            if step.gives is not None:
                schema = type_to_json_schema(step.gives.type)
                (steps_dir / f"{prefix}.schema.json").write_text(
                    json.dumps(schema, indent=2) + "\n"
                )
            return

        # exact step
        if not step.takes and step.gives is None:
            body = _STEP_NO_FIELDS.format(name=step.name, mode=step.mode)
        else:
            io_doc = "\n".join(_field_doc(f) for f in step.takes)
            if step.gives:
                io_doc += f"\nGIVES: {step.gives.name}: {_render_type(step.gives.type)}"
            argparse_block = "\n".join(
                f'    parser.add_argument("--{f.name}", required=True)'
                for f in step.takes
            )
            out_name = step.gives.name if step.gives else "result"
            assigned_from = step.takes[0].name if step.takes else '""'
            assignment = f"{out_name} = args.{assigned_from}  # echo: TODO replace with real logic"
            body = _EXACT_STEP_TEMPLATE.format(
                name=step.name,
                mode=step.mode,
                io_doc=io_doc,
                argparse_block=argparse_block,
                body=assignment,
                out_name=out_name,
            )
        (steps_dir / f"{prefix}.py").write_text(body)


def _render_prompt(step: StepIR) -> str:
    input_block = "\n".join(f"  {f.name}: ${{{f.name}}}" for f in step.takes) or "  (no inputs)"
    return _JUDGMENT_PROMPT_TEMPLATE.format(name=step.name, input_block=input_block)


def _field_doc(f: FieldIR) -> str:
    return f"TAKES: {f.name}: {_render_type(f.type)}"


def _render_type(t) -> str:
    if isinstance(t, PrimitiveType):
        return t.name
    return type(t).__name__
