"""target: claude-workflow — emits a Claude Code Workflow script (JS)."""
from __future__ import annotations

import sys
from pathlib import Path

from clio.emitters._workflow_flow_renderer import render_flow_js
from clio.emitters._workflow_helpers import (
    entry_flow,
    render_meta,
    validate_graph_for_workflow,
    workflow_name,
)
from clio.emitters._workflow_step_renderers import (
    render_exact_step_js,
    render_judgment_step_js,
)
from clio.emitters.base import BaseEmitter
from clio.ir.graph import (
    CallIR,
    FlowGraph,
    FlowIR,
    ForEachIR,
    IfBlockIR,
    MatchBlockIR,
    StepIR,
    WhileBlockIR,
)

_HEADER = """\
// Generated by CLIO — target: claude-workflow — FLOW {flow}
//
// Install: copy this file into .claude/workflows/, then run it from Claude Code.
// Judgment steps run as subagents. Exact steps are stubs that throw until you
// fill them in, with PURE JavaScript: the sandbox has no filesystem, no network,
// no process and no clock (Date.now(), new Date() and Math.random() throw).
"""


def _collect_reachable_steps(
    flow: FlowIR, steps_by_name: dict[str, StepIR]
) -> list[StepIR]:
    """Every step reachable from the entry flow, first-seen order, no duplicates.

    Scoped to the entry flow — unlike swift.py:38, which walks graph.flows. This
    target emits one script for exactly one FLOW (E_WF_006), so a step that only
    another FLOW calls has no call site here: emitting its function would leave
    dead code in the file the author has to read and fill in.

    Deduping is not cosmetic. The script is an ES module, module code is strict
    code, and declaring the same function twice in strict code is a SyntaxError —
    a step called twice in the chain must still be emitted once.

    ON_FAIL fallback chains are followed for the reason swift follows them: their
    call sites are emitted (Task 10), so the functions they call must exist.
    """
    seen: set[str] = set()
    ordered: list[StepIR] = []

    def collect(step: StepIR) -> None:
        if step.name in seen:
            return
        seen.add(step.name)
        ordered.append(step)
        if step.on_fail is not None:
            for strategy in step.on_fail.strategies:
                if strategy.kind == "fallback" and strategy.fallback_step is not None:
                    collect(strategy.fallback_step)

    def visit(items: tuple[object, ...]) -> None:
        for item in items:
            if isinstance(item, CallIR):
                step = steps_by_name.get(item.step_name)
                if step is not None:
                    collect(step)
            elif isinstance(item, IfBlockIR):
                visit(item.then_body)
                visit(item.else_body)
            elif isinstance(item, MatchBlockIR):
                for case in item.cases:
                    visit(case.body)
            elif isinstance(item, WhileBlockIR):
                visit(item.body)
            elif isinstance(item, ForEachIR):
                visit(item.body)
            # FlowCallIR names a sub-flow, not a step — inlined in Task 9.

    visit(flow.chain)
    for rescue in flow.rescues:
        visit(rescue.body)
    return ordered


def render_script(graph: FlowGraph) -> str:
    """The whole script: header, meta, step functions, flow body.

    Order is for the reader, not the parser — function declarations hoist. The
    author lands on `meta`, scrolls through the steps they may have to fill in, and
    reads the orchestration last, where the state threading is visible in one page.
    """
    flow = entry_flow(graph)
    contracts = {c.name: c for c in graph.contracts}
    steps_by_name = {s.name: s for s in graph.steps}

    parts = [_HEADER.format(flow=flow.name), render_meta(graph) + "\n"]
    for step in _collect_reachable_steps(flow, steps_by_name):
        parts.append(
            render_exact_step_js(step, contracts)
            if step.mode == "exact"
            else render_judgment_step_js(step, contracts)
        )
    parts.append(render_flow_js(flow, steps_by_name))
    return "\n".join(parts)


class WorkflowEmitter(BaseEmitter):
    def emit(
        self,
        graph: FlowGraph,
        output_dir: Path,
        *,
        source_path: Path | None = None,
        sources: tuple[Path, ...] | None = None,
    ) -> None:
        warn = lambda m: print(m, file=sys.stderr)  # noqa: E731
        validate_graph_for_workflow(graph, warn)
        output_dir.mkdir(parents=True, exist_ok=True)
        name = workflow_name(graph)
        (output_dir / f"{name}.workflow.js").write_text(render_script(graph))
