// Auto-generated by CLIO. Do not edit by hand.
import Foundation

struct CustomerRisk: Codable, Sendable {
    var client: String
    var risk: String
    var reason: String

    static let jsonSchema = """
    {
      "type": "object",
      "properties": {
        "client": {
          "type": "string"
        },
        "risk": {
          "enum": [
            "low",
            "mid",
            "high"
          ]
        },
        "reason": {
          "type": "string",
          "maxLength": 300
        }
      },
      "required": [
        "client",
        "risk",
        "reason"
      ],
      "additionalProperties": false,
      "x-clio-assert": {
        "kind": "compare",
        "op": ">",
        "left": {
          "kind": "call",
          "func": "len",
          "args": [
            {
              "kind": "ident",
              "name": "reason"
            }
          ]
        },
        "right": {
          "kind": "int",
          "value": 0
        }
      }
    }
    """

    func validate() throws {
        try Validate.check(self, against: Self.jsonSchema)
    }
}
