package steps

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/anthropics/anthropic-sdk-go"
	"pipeline/clio_runtime/cache"
)

type ClassifyIn struct {
	Item string `json:"item"`
}

type ClassifyOut struct {
	Label string `json:"label"`
}

// Classify implements the 'classify' judgment step (Anthropic SDK).
func Classify(ctx context.Context, in ClassifyIn) (ClassifyOut, error) {
	// 1. Build prompt from input.
	inJSON, err := json.Marshal(in)
	if err != nil {
		return ClassifyOut{}, fmt.Errorf("classify: marshal input: %w", err)
	}
	prompt := fmt.Sprintf("Process this input and return JSON matching the output schema.\n\nInput:\n%s", string(inJSON))

	ttl := int64(86400)
	ttlPtr := &ttl
	cacheDir := cache.CacheDirFromEnv()
	key := cache.Key("classify", "claude-haiku-4-5-20251001", prompt, "")
	if v, ok := cache.Lookup(cacheDir, "classify", key, ttlPtr); ok {
		var cached ClassifyOut
		if err := json.Unmarshal([]byte(v), &cached); err == nil {
			return cached, nil
		}
	}

	client := anthropic.NewClient()
	resp, err := client.Messages.New(ctx, anthropic.MessageNewParams{
		Model:     "claude-haiku-4-5-20251001",
		MaxTokens: int64(8192),
		System: []anthropic.TextBlockParam{{Text: "You are a precise function. Return only valid JSON matching the requested output schema. No prose."}},
		Messages: []anthropic.MessageParam{anthropic.NewUserMessage(anthropic.NewTextBlock(prompt))},
	})
	if err != nil {
		return ClassifyOut{}, fmt.Errorf("classify: anthropic: %w", err)
	}
	if len(resp.Content) == 0 {
		return ClassifyOut{}, fmt.Errorf("classify: empty response")
	}
	raw := resp.Content[0].Text
	var out ClassifyOut
	if err := json.Unmarshal([]byte(raw), &out); err != nil {
		return ClassifyOut{}, fmt.Errorf("classify: unmarshal: %w", err)
	}
	// Validate per contract.
	if validatable, ok := any(&out).(interface{ Validate(context.Context) error }); ok {
		if err := validatable.Validate(ctx); err != nil {
			return ClassifyOut{}, fmt.Errorf("classify: validate: %w", err)
		}
	}
	if rawBytes, err := json.Marshal(out); err == nil {
		_ = cache.Store(cacheDir, "classify", key, "claude-haiku-4-5-20251001", string(rawBytes))
	}
	return out, nil
}
