package flow

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"

	"pipeline/steps"
)

func Run(ctx context.Context, kwargs map[string]any) (map[string]any, error) {
	state := map[string]any{}

	loadOut, err := steps.Load(ctx, steps.LoadIn{ File: "customers.csv" })
	if err != nil {
		return nil, err
	}
	state["customers"] = loadOut

	detect_churnOut, err := steps.DetectChurn(ctx, steps.DetectChurnIn{ Customers: state["customers"].(steps.LoadOut).Customers })
	if err != nil {
		return nil, err
	}
	state["risks"] = detect_churnOut

	return state, nil
}
