// Auto-generated by CLIO. Do not edit by hand.
// Zero-dependency Anthropic Messages API client for judgment steps.
// Uses Foundation (URLSession) only — no external SDKs.
// Cross-platform: imports FoundationNetworking on Linux where URLSession lives.
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Foundation

// MARK: - AnthropicError

struct AnthropicError: Error {
    let message: String
    var localizedDescription: String { message }
}

// MARK: - Anthropic

/// Thin URLSession wrapper over the Anthropic Messages API.
/// Returns the text content of the first content block.
enum Anthropic {

    /// Call the Anthropic Messages API and return the assistant's text reply.
    ///
    /// - Parameters:
    ///   - model:     Anthropic model ID (e.g. "claude-haiku-4-5-20251001")
    ///   - system:    System-prompt text (the JSON-only directive)
    ///   - prompt:    User-turn text (the serialised step input)
    ///   - maxTokens: Maximum tokens to generate
    /// - Returns: The raw text from `response.content[0].text`
    /// - Throws:  `AnthropicError` when the API key is missing, the HTTP call
    ///            fails, or the response shape is unexpected.
    static func complete(
        model: String,
        system: String,
        prompt: String,
        maxTokens: Int
    ) async throws -> String {
        guard let apiKey = ProcessInfo.processInfo.environment["ANTHROPIC_API_KEY"],
              !apiKey.isEmpty else {
            throw AnthropicError(message: "ANTHROPIC_API_KEY is not set or is empty")
        }

        guard let url = URL(string: "https://api.anthropic.com/v1/messages") else {
            throw AnthropicError(message: "internal: invalid Anthropic API URL")
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(apiKey, forHTTPHeaderField: "x-api-key")
        request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        request.setValue("application/json", forHTTPHeaderField: "content-type")

        let body: [String: Any] = [
            "model": model,
            "max_tokens": maxTokens,
            "system": system,
            "messages": [["role": "user", "content": prompt]]
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        return try await withCheckedThrowingContinuation { continuation in
            URLSession.shared.dataTask(with: request) { data, _, error in
                if let error = error {
                    continuation.resume(throwing: error)
                    return
                }
                guard let data = data else {
                    continuation.resume(throwing: AnthropicError(
                        message: "Anthropic: empty response body"))
                    return
                }
                do {
                    guard let json = try JSONSerialization.jsonObject(with: data)
                            as? [String: Any] else {
                        let preview = String(data: data.prefix(200), encoding: .utf8)
                            ?? "<non-UTF8>"
                        throw AnthropicError(
                            message: "Anthropic: response is not a JSON object: \(preview)")
                    }
                    // Surface API-level error messages before attempting to parse content.
                    if let errObj = json["error"] as? [String: Any],
                       let errMsg = errObj["message"] as? String {
                        throw AnthropicError(message: "Anthropic API error: \(errMsg)")
                    }
                    guard let content = json["content"] as? [[String: Any]],
                          let first = content.first,
                          let text = first["text"] as? String else {
                        let preview = String(data: data.prefix(200), encoding: .utf8)
                            ?? "<non-UTF8>"
                        throw AnthropicError(
                            message: "Anthropic: unexpected response shape: \(preview)")
                    }
                    continuation.resume(returning: text)
                } catch {
                    continuation.resume(throwing: error)
                }
            }.resume()
        }
    }
}
