// Auto-generated by CLIO. Do not edit by hand.
// Cache layout matches clio/runtime/cache.py and clio_runtime/cache/cache.go
// byte-for-byte so cache files are interchangeable across targets.
//
// Key derivation (identical to Python and Go targets):
//   SHA256(step + "\n" + model + "\n" + prompt + "\n" + schemaJSON)
//
// On disk: <cache_dir>/<step_name>/<sha256>.json
//   {"created_at": <epoch>, "model": "<m>", "response": "<raw>"}
import Foundation

// MARK: - Cache

enum Cache {

    /// Derive the cache key.
    /// Formula is byte-identical to clio/runtime/cache.py::cache_key and
    /// clio_runtime/cache/cache.go::Key.
    static func key(step: String, model: String, prompt: String, schema: String) -> String {
        let payload = [step, model, prompt, schema].joined(separator: "\n")
        return sha256Hex(payload)
    }

    /// Return the cached response string, or nil on miss or staleness.
    ///
    /// - Parameters:
    ///   - ttlSeconds: nil for permanent (CACHE: on); positive integer for TTL (CACHE: ttl(…))
    static func lookup(
        cacheDir: String,
        stepName: String,
        key: String,
        ttlSeconds: Int?
    ) -> String? {
        let path = URL(fileURLWithPath: cacheDir)
            .appendingPathComponent(stepName)
            .appendingPathComponent("\(key).json")
        guard
            let data = try? Data(contentsOf: path),
            let obj  = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
            let response = obj["response"] as? String
        else { return nil }
        if let ttl = ttlSeconds {
            let createdAt = (obj["created_at"] as? NSNumber)?.doubleValue ?? 0.0
            let age = Date().timeIntervalSince1970 - createdAt
            if age >= Double(ttl) { return nil }
        }
        return response
    }

    /// Write a cache entry atomically (write to .tmp then rename).
    static func store(
        cacheDir: String,
        stepName: String,
        key: String,
        model: String,
        response: String
    ) {
        let dir = URL(fileURLWithPath: cacheDir).appendingPathComponent(stepName)
        try? FileManager.default.createDirectory(
            at: dir, withIntermediateDirectories: true, attributes: nil
        )
        let final = dir.appendingPathComponent("\(key).json")
        let tmp   = dir.appendingPathComponent("\(key).json.tmp")
        let entry: [String: Any] = [
            "created_at": Int(Date().timeIntervalSince1970),
            "model":      model,
            "response":   response,
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: entry) else { return }
        try? data.write(to: tmp)
        try? FileManager.default.moveItem(at: tmp, to: final)
    }

    /// Return CLIO_CACHE_DIR env var or ".cache" — mirrors CacheDirFromEnv() in cache.go.
    static func cacheDirFromEnv() -> String {
        ProcessInfo.processInfo.environment["CLIO_CACHE_DIR"] ?? ".cache"
    }
}
