// Auto-generated by CLIO. Do not edit by hand.
// FIPS 180-4 SHA-256 — vendored pure-Swift implementation.
// No CryptoKit, no CommonCrypto — byte-stable on all platforms.
//
// Public API:
//   sha256Hex(_ bytes: [UInt8]) -> String
//   sha256Hex(_ s: String)      -> String

// MARK: - Round constants (fractional parts of cube roots of first 64 primes)

private let _k256: [UInt32] = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
    0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
    0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
    0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
    0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
    0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

// MARK: - Public API

/// Return the lowercase hex-encoded SHA-256 digest of `bytes`.
func sha256Hex(_ bytes: [UInt8]) -> String {
    var chars = [Character]()
    chars.reserveCapacity(64)
    for b in _sha256Digest(bytes) {
        let hi = UInt32(b >> 4)
        let lo = UInt32(b & 0xf)
        // 48 = '0', 97 = 'a'; 87 = 97 - 10
        chars.append(Character(UnicodeScalar(hi < 10 ? 48 + hi : 87 + hi)!))
        chars.append(Character(UnicodeScalar(lo < 10 ? 48 + lo : 87 + lo)!))
    }
    return String(chars)
}

/// Return the lowercase hex-encoded SHA-256 digest of the UTF-8 encoding of `s`.
func sha256Hex(_ s: String) -> String {
    sha256Hex([UInt8](s.utf8))
}

// MARK: - Internal

private func _rotr32(_ x: UInt32, _ n: UInt32) -> UInt32 {
    (x >> n) | (x << (32 &- n))
}

private func _sha256Digest(_ message: [UInt8]) -> [UInt8] {
    // Initial hash values (fractional parts of square roots of first 8 primes)
    var h0: UInt32 = 0x6a09e667
    var h1: UInt32 = 0xbb67ae85
    var h2: UInt32 = 0x3c6ef372
    var h3: UInt32 = 0xa54ff53a
    var h4: UInt32 = 0x510e527f
    var h5: UInt32 = 0x9b05688c
    var h6: UInt32 = 0x1f83d9ab
    var h7: UInt32 = 0x5be0cd19

    // Pre-processing: padding
    var msg = message
    let bitLen = UInt64(message.count) &* 8
    msg.append(0x80)
    while (msg.count % 64) != 56 {
        msg.append(0x00)
    }
    // Append original bit-length as 64-bit big-endian integer
    msg.append(UInt8((bitLen >> 56) & 0xff))
    msg.append(UInt8((bitLen >> 48) & 0xff))
    msg.append(UInt8((bitLen >> 40) & 0xff))
    msg.append(UInt8((bitLen >> 32) & 0xff))
    msg.append(UInt8((bitLen >> 24) & 0xff))
    msg.append(UInt8((bitLen >> 16) & 0xff))
    msg.append(UInt8((bitLen >>  8) & 0xff))
    msg.append(UInt8( bitLen        & 0xff))

    // Process each 64-byte (512-bit) block
    for blockStart in stride(from: 0, to: msg.count, by: 64) {
        var w = [UInt32](repeating: 0, count: 64)
        for i in 0..<16 {
            let b = blockStart + i * 4
            w[i] = (UInt32(msg[b])   << 24)
                 | (UInt32(msg[b+1]) << 16)
                 | (UInt32(msg[b+2]) <<  8)
                 |  UInt32(msg[b+3])
        }
        for i in 16..<64 {
            let s0 = _rotr32(w[i-15], 7) ^ _rotr32(w[i-15], 18) ^ (w[i-15] >> 3)
            let s1 = _rotr32(w[i-2], 17) ^ _rotr32(w[i-2], 19)  ^ (w[i-2]  >> 10)
            w[i] = w[i-16] &+ s0 &+ w[i-7] &+ s1
        }

        var a = h0, b = h1, c = h2, d = h3
        var e = h4, f = h5, g = h6, hh = h7

        for i in 0..<64 {
            let S1    = _rotr32(e, 6)  ^ _rotr32(e, 11) ^ _rotr32(e, 25)
            let ch    = (e & f) ^ (~e & g)
            let temp1 = hh &+ S1 &+ ch &+ _k256[i] &+ w[i]
            let S0    = _rotr32(a, 2)  ^ _rotr32(a, 13) ^ _rotr32(a, 22)
            let maj   = (a & b) ^ (a & c) ^ (b & c)
            let temp2 = S0 &+ maj
            hh = g; g = f; f = e
            e  = d &+ temp1
            d  = c; c = b; b = a
            a  = temp1 &+ temp2
        }

        h0 = h0 &+ a; h1 = h1 &+ b; h2 = h2 &+ c; h3 = h3 &+ d
        h4 = h4 &+ e; h5 = h5 &+ f; h6 = h6 &+ g; h7 = h7 &+ hh
    }

    // Produce final 32-byte digest (big-endian)
    var digest = [UInt8](repeating: 0, count: 32)
    for (i, h) in [h0, h1, h2, h3, h4, h5, h6, h7].enumerated() {
        digest[i * 4]     = UInt8((h >> 24) & 0xff)
        digest[i * 4 + 1] = UInt8((h >> 16) & 0xff)
        digest[i * 4 + 2] = UInt8((h >>  8) & 0xff)
        digest[i * 4 + 3] = UInt8( h        & 0xff)
    }
    return digest
}
