package cache

// Auto-generated by CLIO. Cache layout matches clio/runtime/cache.py
// byte-for-byte so cache files are interchangeable with the python target.
//
// On disk: <cache_dir>/<step_name>/<sha256>.json
//   {"created_at": <epoch>, "model": "<m>", "response": "<raw>"}

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Key derives the cache key. Identical formula to clio/runtime/cache.py:
// SHA256(step + "\n" + model + "\n" + prompt + "\n" + schemaJSON).
func Key(step, model, prompt, schemaJSON string) string {
	payload := strings.Join([]string{step, model, prompt, schemaJSON}, "\n")
	sum := sha256.Sum256([]byte(payload))
	return hex.EncodeToString(sum[:])
}

// Lookup returns (response, true) if the cache entry is present and fresh.
// ttlSeconds: nil for permanent (CACHE: on), 0 to skip, positive for ttl.
func Lookup(cacheDir, stepName, key string, ttlSeconds *int64) (string, bool) {
	if ttlSeconds != nil && *ttlSeconds == 0 {
		return "", false
	}
	path := filepath.Join(cacheDir, stepName, key+".json")
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	var entry struct {
		CreatedAt int64  `json:"created_at"`
		Model     string `json:"model"`
		Response  string `json:"response"`
	}
	if err := json.Unmarshal(raw, &entry); err != nil {
		return "", false
	}
	if ttlSeconds != nil {
		if time.Now().Unix()-entry.CreatedAt >= *ttlSeconds {
			return "", false
		}
	}
	return entry.Response, true
}

// Store writes a cache entry atomically.
func Store(cacheDir, stepName, key, model, response string) error {
	dir := filepath.Join(cacheDir, stepName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	entry := map[string]any{
		"created_at": time.Now().Unix(),
		"model":      model,
		"response":   response,
	}
	body, err := json.Marshal(entry)
	if err != nil {
		return err
	}
	tmp := filepath.Join(dir, key+".json.tmp")
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return err
	}
	final := filepath.Join(dir, key+".json")
	return os.Rename(tmp, final)
}

// CacheDirFromEnv returns CLIO_CACHE_DIR or the relative path ".cache".
// Mirrors the python emitter's clio/emitters/python.py fallback so both
// targets resolve the cache directory relative to the same CWD.
func CacheDirFromEnv() string {
	if d := os.Getenv("CLIO_CACHE_DIR"); d != "" {
		return d
	}
	return ".cache"
}
