package flow

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"

	"golang.org/x/sync/errgroup"

	"pipeline/steps"
)

func Run(ctx context.Context, kwargs map[string]any) (map[string]any, error) {
	state := map[string]any{}

	loadOut, err := steps.Load(ctx, steps.LoadIn{ File: "in.csv" })
	if err != nil {
		return nil, err
	}
	state["items"] = loadOut

	{
		_items := state["items"].(steps.LoadOut).Items
		_results := make([]any, len(_items))
		g, ctx := errgroup.WithContext(ctx)
		g.SetLimit(10)
		for _i, item := range _items {
			g.Go(func() error {
				classifyOut, err := steps.Classify(ctx, steps.ClassifyIn{ Item: item })
				if err != nil {
					return err
				}

				_results[_i] = classifyOut
				return nil
			})
		}
		if err := g.Wait(); err != nil {
			return nil, err
		}
		state["labels"] = _results
	}

	return state, nil
}
