package validate

// Auto-generated by CLIO. Do not edit by hand.

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

// Schema validates `instance` against the given JSON Schema string.
// Also evaluates an x-clio-assert clause if present (CLIO's compact assert AST).
func Schema(ctx context.Context, schemaJSON string, instance any) error {
	var raw any
	if err := json.Unmarshal([]byte(schemaJSON), &raw); err != nil {
		return fmt.Errorf("validate: invalid schema JSON: %w", err)
	}
	compiler := jsonschema.NewCompiler()
	if err := compiler.AddResource("file:///schema.json", raw); err != nil {
		return fmt.Errorf("validate: add schema: %w", err)
	}
	sch, err := compiler.Compile("file:///schema.json")
	if err != nil {
		return fmt.Errorf("validate: compile schema: %w", err)
	}
	if err := sch.Validate(instance); err != nil {
		return fmt.Errorf("validate: schema: %w", err)
	}
	if m, ok := raw.(map[string]any); ok {
		if assertNode, ok := m["x-clio-assert"]; ok {
			if !evalAssert(assertNode, instance) {
				return fmt.Errorf("validate: x-clio-assert failed")
			}
		}
	}
	return nil
}

// evalAssert walks the compact CLIO assert AST. Node kinds: ident, int, float,
// str, call(len, ...), compare(==,!=,<,>,<=,>=). Any other kind is treated as
// false (defensive). The walker is a direct port of clio/runtime/validate.py.
func evalAssert(node any, ctx any) bool {
	m, ok := node.(map[string]any)
	if !ok {
		return false
	}
	kind, _ := m["kind"].(string)
	switch kind {
	case "ident":
		// Resolve from ctx (must be a map[string]any in this codebase).
		if obj, ok := ctx.(map[string]any); ok {
			_, ok := obj[m["name"].(string)]
			return ok
		}
		return false
	case "int", "float", "str":
		return true
	case "call":
		fn, _ := m["func"].(string)
		if fn != "len" {
			return false
		}
		args, _ := m["args"].([]any)
		if len(args) != 1 {
			return false
		}
		return lenOf(args[0], ctx) >= 0
	case "compare":
		left := resolve(m["left"], ctx)
		right := resolve(m["right"], ctx)
		op, _ := m["op"].(string)
		return cmpOk(left, right, op)
	}
	return false
}

func resolve(node any, ctx any) any {
	m, _ := node.(map[string]any)
	switch m["kind"] {
	case "ident":
		if obj, ok := ctx.(map[string]any); ok {
			return obj[m["name"].(string)]
		}
		return nil
	case "int":
		return int64(m["value"].(float64))
	case "float":
		return m["value"]
	case "str":
		return m["value"]
	case "call":
		// Only len() is supported today; mirror evalAssert's guard.
		if fn, _ := m["func"].(string); fn != "len" {
			return nil
		}
		return lenOf(m["args"].([]any)[0], ctx)
	}
	return nil
}

func lenOf(node any, ctx any) int64 {
	v := resolve(node, ctx)
	switch s := v.(type) {
	case string:
		return int64(len(s))
	case []any:
		return int64(len(s))
	case map[string]any:
		return int64(len(s))
	}
	return -1
}

func cmpOk(l, r any, op string) bool {
	lf, lok := toFloat(l)
	rf, rok := toFloat(r)
	if lok && rok {
		switch op {
		case "==":
			return lf == rf
		case "!=":
			return lf != rf
		case "<":
			return lf < rf
		case ">":
			return lf > rf
		case "<=":
			return lf <= rf
		case ">=":
			return lf >= rf
		}
	}
	ls, lsOk := l.(string)
	rs, rsOk := r.(string)
	if lsOk && rsOk {
		switch op {
		case "==":
			return ls == rs
		case "!=":
			return ls != rs
		}
	}
	return false
}

func toFloat(v any) (float64, bool) {
	switch n := v.(type) {
	case int64:
		return float64(n), true
	case float64:
		return n, true
	}
	return 0, false
}
