"""Step: echo_str (mode=exact)

TAKES: input: str
GIVES: output: str

Auto-generated by clio. Do not edit by hand — re-run `clio compile`.
"""

import argparse
import json
import sys
from pathlib import Path


STATE_FILE = Path(__file__).resolve().parent.parent / "state.json"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    args = parser.parse_args()

    output = args.input  # echo: TODO replace with real logic

    state = json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}
    state["output"] = output
    STATE_FILE.write_text(json.dumps(state, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
